// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `network.AddDataCollectorParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddDataCollectorParameters {
    #[serde(rename = "dataTypes")]
    pub data_types: Vec<crate::network::DataType>,
    #[serde(rename = "maxEncodedDataSize")]
    pub max_encoded_data_size: u64,
    #[serde(rename = "collectorType", skip_serializing_if = "Option::is_none")]
    pub collector_type: Option<crate::network::CollectorType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `network.AddDataCollectorResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddDataCollectorResult {
    pub collector: crate::network::Collector,
}

/// `network.AddInterceptParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddInterceptParameters {
    pub phases: Vec<crate::network::InterceptPhase>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "urlPatterns", skip_serializing_if = "Option::is_none")]
    pub url_patterns: Option<Vec<crate::network::UrlPattern>>,
}

/// `network.AddInterceptResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddInterceptResult {
    pub intercept: crate::network::Intercept,
}

/// `network.AuthChallenge`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AuthChallenge {
    pub scheme: String,
    pub realm: String,
}

/// `network.AuthCredentials`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AuthCredentials {
    #[serde(rename = "type")]
    pub type_: String,
    pub username: String,
    pub password: String,
}

/// `network.AuthRequiredParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AuthRequiredParameters {
    #[serde(flatten)]
    pub base_parameters: crate::network::BaseParameters,
    pub response: crate::network::ResponseData,
}

/// `network.Base64Value`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Base64Value {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `network.BaseParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BaseParameters {
    pub context: JsonValue,
    #[serde(rename = "isBlocked")]
    pub is_blocked: bool,
    pub navigation: JsonValue,
    #[serde(rename = "redirectCount")]
    pub redirect_count: u64,
    pub request: crate::network::RequestData,
    pub timestamp: u64,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub intercepts: Option<Vec<crate::network::Intercept>>,
}

/// `network.BeforeRequestSentParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BeforeRequestSentParameters {
    #[serde(flatten)]
    pub base_parameters: crate::network::BaseParameters,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub initiator: Option<crate::network::Initiator>,
}

/// `network.BytesValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum BytesValue {
    StringValue(crate::network::StringValue),
    Base64Value(crate::network::Base64Value),
}

/// `network.Collector`
pub type Collector = String;

/// `network.CollectorType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum CollectorType {
    #[serde(rename = "blob")]
    Blob,
}

/// `network.ContinueRequestParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContinueRequestParameters {
    pub request: crate::network::Request,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<crate::network::BytesValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cookies: Option<Vec<crate::network::CookieHeader>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<crate::network::Header>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

/// `network.ContinueRequestResult`
pub type ContinueRequestResult = crate::EmptyResult;

/// `network.ContinueResponseParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContinueResponseParameters {
    pub request: crate::network::Request,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cookies: Option<Vec<crate::network::SetCookieHeader>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub credentials: Option<crate::network::AuthCredentials>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<crate::network::Header>>,
    #[serde(rename = "reasonPhrase", skip_serializing_if = "Option::is_none")]
    pub reason_phrase: Option<String>,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<u64>,
}

/// `network.ContinueResponseResult`
pub type ContinueResponseResult = crate::EmptyResult;

/// `network.ContinueWithAuthCredentials`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContinueWithAuthCredentials {
    pub action: String,
    pub credentials: crate::network::AuthCredentials,
}

/// `network.ContinueWithAuthNoCredentials`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContinueWithAuthNoCredentials {
    pub action: JsonValue,
}

/// `network.ContinueWithAuthParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContinueWithAuthParameters {
    pub request: crate::network::Request,
}

/// `network.ContinueWithAuthResult`
pub type ContinueWithAuthResult = crate::EmptyResult;

/// `network.Cookie`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Cookie {
    pub name: String,
    pub value: crate::network::BytesValue,
    pub domain: String,
    pub path: String,
    pub size: u64,
    #[serde(rename = "httpOnly")]
    pub http_only: bool,
    pub secure: bool,
    #[serde(rename = "sameSite")]
    pub same_site: crate::network::SameSite,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry: Option<u64>,
}

/// `network.CookieHeader`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CookieHeader {
    pub name: String,
    pub value: crate::network::BytesValue,
}

/// `network.DataType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DataType {
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "response")]
    Response,
}

/// `network.DisownDataParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DisownDataParameters {
    #[serde(rename = "dataType")]
    pub data_type: crate::network::DataType,
    pub collector: crate::network::Collector,
    pub request: crate::network::Request,
}

/// `network.DisownDataResult`
pub type DisownDataResult = crate::EmptyResult;

/// `network.FailRequestParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FailRequestParameters {
    pub request: crate::network::Request,
}

/// `network.FailRequestResult`
pub type FailRequestResult = crate::EmptyResult;

/// `network.FetchErrorParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FetchErrorParameters {
    #[serde(flatten)]
    pub base_parameters: crate::network::BaseParameters,
    #[serde(rename = "errorText")]
    pub error_text: String,
}

/// `network.FetchTimingInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FetchTimingInfo {
    #[serde(rename = "timeOrigin")]
    pub time_origin: f64,
    #[serde(rename = "requestTime")]
    pub request_time: f64,
    #[serde(rename = "redirectStart")]
    pub redirect_start: f64,
    #[serde(rename = "redirectEnd")]
    pub redirect_end: f64,
    #[serde(rename = "fetchStart")]
    pub fetch_start: f64,
    #[serde(rename = "dnsStart")]
    pub dns_start: f64,
    #[serde(rename = "dnsEnd")]
    pub dns_end: f64,
    #[serde(rename = "connectStart")]
    pub connect_start: f64,
    #[serde(rename = "connectEnd")]
    pub connect_end: f64,
    #[serde(rename = "tlsStart")]
    pub tls_start: f64,
    #[serde(rename = "requestStart")]
    pub request_start: f64,
    #[serde(rename = "responseStart")]
    pub response_start: f64,
    #[serde(rename = "responseEnd")]
    pub response_end: f64,
}

/// `network.GetDataParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetDataParameters {
    #[serde(rename = "dataType")]
    pub data_type: crate::network::DataType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub collector: Option<crate::network::Collector>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub disown: Option<bool>,
    pub request: crate::network::Request,
}

/// `network.GetDataResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetDataResult {
    pub bytes: crate::network::BytesValue,
}

/// `network.Header`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Header {
    pub name: String,
    pub value: crate::network::BytesValue,
}

/// `network.Initiator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Initiator {
    #[serde(rename = "columnNumber", skip_serializing_if = "Option::is_none")]
    pub column_number: Option<u64>,
    #[serde(rename = "lineNumber", skip_serializing_if = "Option::is_none")]
    pub line_number: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request: Option<crate::network::Request>,
    #[serde(rename = "stackTrace", skip_serializing_if = "Option::is_none")]
    pub stack_trace: Option<crate::script::StackTrace>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<JsonValue>,
}

/// `network.Intercept`
pub type Intercept = String;

/// `network.InterceptPhase`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum InterceptPhase {
    #[serde(rename = "beforeRequestSent")]
    BeforeRequestSent,
    #[serde(rename = "responseStarted")]
    ResponseStarted,
    #[serde(rename = "authRequired")]
    AuthRequired,
}

/// `network.ProvideResponseParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ProvideResponseParameters {
    pub request: crate::network::Request,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<crate::network::BytesValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cookies: Option<Vec<crate::network::SetCookieHeader>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<Vec<crate::network::Header>>,
    #[serde(rename = "reasonPhrase", skip_serializing_if = "Option::is_none")]
    pub reason_phrase: Option<String>,
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<u64>,
}

/// `network.ProvideResponseResult`
pub type ProvideResponseResult = crate::EmptyResult;

/// `network.RemoveDataCollectorParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RemoveDataCollectorParameters {
    pub collector: crate::network::Collector,
}

/// `network.RemoveDataCollectorResult`
pub type RemoveDataCollectorResult = crate::EmptyResult;

/// `network.RemoveInterceptParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RemoveInterceptParameters {
    pub intercept: crate::network::Intercept,
}

/// `network.RemoveInterceptResult`
pub type RemoveInterceptResult = crate::EmptyResult;

/// `network.Request`
pub type Request = String;

/// `network.RequestData`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RequestData {
    pub request: crate::network::Request,
    pub url: String,
    pub method: String,
    pub headers: Vec<crate::network::Header>,
    pub cookies: Vec<crate::network::Cookie>,
    #[serde(rename = "headersSize")]
    pub headers_size: u64,
    #[serde(rename = "bodySize")]
    pub body_size: JsonValue,
    pub destination: String,
    #[serde(rename = "initiatorType")]
    pub initiator_type: JsonValue,
    pub timings: crate::network::FetchTimingInfo,
}

/// `network.ResponseCompletedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ResponseCompletedParameters {
    #[serde(flatten)]
    pub base_parameters: crate::network::BaseParameters,
    pub response: crate::network::ResponseData,
}

/// `network.ResponseContent`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ResponseContent {
    pub size: u64,
}

/// `network.ResponseData`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ResponseData {
    pub url: String,
    pub protocol: String,
    pub status: u64,
    #[serde(rename = "statusText")]
    pub status_text: String,
    #[serde(rename = "fromCache")]
    pub from_cache: bool,
    pub headers: Vec<crate::network::Header>,
    #[serde(rename = "mimeType")]
    pub mime_type: String,
    #[serde(rename = "bytesReceived")]
    pub bytes_received: u64,
    #[serde(rename = "headersSize")]
    pub headers_size: JsonValue,
    #[serde(rename = "bodySize")]
    pub body_size: JsonValue,
    pub content: crate::network::ResponseContent,
    #[serde(rename = "authChallenges", skip_serializing_if = "Option::is_none")]
    pub auth_challenges: Option<Vec<crate::network::AuthChallenge>>,
}

/// `network.ResponseStartedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ResponseStartedParameters {
    #[serde(flatten)]
    pub base_parameters: crate::network::BaseParameters,
    pub response: crate::network::ResponseData,
}

/// `network.SameSite`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SameSite {
    #[serde(rename = "strict")]
    Strict,
    #[serde(rename = "lax")]
    Lax,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "default")]
    Default,
}

/// `network.SetCacheBehaviorParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetCacheBehaviorParameters {
    #[serde(rename = "cacheBehavior")]
    pub cache_behavior: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
}

/// `network.SetCacheBehaviorResult`
pub type SetCacheBehaviorResult = crate::EmptyResult;

/// `network.SetCookieHeader`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetCookieHeader {
    pub name: String,
    pub value: crate::network::BytesValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(rename = "httpOnly", skip_serializing_if = "Option::is_none")]
    pub http_only: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry: Option<String>,
    #[serde(rename = "maxAge", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "sameSite", skip_serializing_if = "Option::is_none")]
    pub same_site: Option<crate::network::SameSite>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
}

/// `network.SetExtraHeadersParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetExtraHeadersParameters {
    pub headers: Vec<crate::network::Header>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `network.SetExtraHeadersResult`
pub type SetExtraHeadersResult = crate::EmptyResult;

/// `network.StringValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StringValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `network.UrlPattern`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum UrlPattern {
    UrlPatternPattern(crate::network::UrlPatternPattern),
    UrlPatternString(crate::network::UrlPatternString),
}

/// `network.UrlPatternPattern`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UrlPatternPattern {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub protocol: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub port: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pathname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub search: Option<String>,
}

/// `network.UrlPatternString`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UrlPatternString {
    #[serde(rename = "type")]
    pub type_: String,
    pub pattern: String,
}

/// `network.addDataCollector`
pub struct AddDataCollector;
impl crate::BidiCommand for AddDataCollector {
    const METHOD: &'static str = "network.addDataCollector";
    type Params = crate::network::AddDataCollectorParameters;
    type Response = crate::network::AddDataCollectorResult;
}

/// `network.addIntercept`
pub struct AddIntercept;
impl crate::BidiCommand for AddIntercept {
    const METHOD: &'static str = "network.addIntercept";
    type Params = crate::network::AddInterceptParameters;
    type Response = crate::network::AddInterceptResult;
}

/// `network.continueRequest`
pub struct ContinueRequest;
impl crate::BidiCommand for ContinueRequest {
    const METHOD: &'static str = "network.continueRequest";
    type Params = crate::network::ContinueRequestParameters;
    type Response = crate::network::ContinueRequestResult;
}

/// `network.continueResponse`
pub struct ContinueResponse;
impl crate::BidiCommand for ContinueResponse {
    const METHOD: &'static str = "network.continueResponse";
    type Params = crate::network::ContinueResponseParameters;
    type Response = crate::network::ContinueResponseResult;
}

/// `network.continueWithAuth`
pub struct ContinueWithAuth;
impl crate::BidiCommand for ContinueWithAuth {
    const METHOD: &'static str = "network.continueWithAuth";
    type Params = crate::network::ContinueWithAuthParameters;
    type Response = crate::network::ContinueWithAuthResult;
}

/// `network.disownData`
pub struct DisownData;
impl crate::BidiCommand for DisownData {
    const METHOD: &'static str = "network.disownData";
    type Params = crate::network::DisownDataParameters;
    type Response = crate::network::DisownDataResult;
}

/// `network.failRequest`
pub struct FailRequest;
impl crate::BidiCommand for FailRequest {
    const METHOD: &'static str = "network.failRequest";
    type Params = crate::network::FailRequestParameters;
    type Response = crate::network::FailRequestResult;
}

/// `network.getData`
pub struct GetData;
impl crate::BidiCommand for GetData {
    const METHOD: &'static str = "network.getData";
    type Params = crate::network::GetDataParameters;
    type Response = crate::network::GetDataResult;
}

/// `network.provideResponse`
pub struct ProvideResponse;
impl crate::BidiCommand for ProvideResponse {
    const METHOD: &'static str = "network.provideResponse";
    type Params = crate::network::ProvideResponseParameters;
    type Response = crate::network::ProvideResponseResult;
}

/// `network.removeDataCollector`
pub struct RemoveDataCollector;
impl crate::BidiCommand for RemoveDataCollector {
    const METHOD: &'static str = "network.removeDataCollector";
    type Params = crate::network::RemoveDataCollectorParameters;
    type Response = crate::network::RemoveDataCollectorResult;
}

/// `network.removeIntercept`
pub struct RemoveIntercept;
impl crate::BidiCommand for RemoveIntercept {
    const METHOD: &'static str = "network.removeIntercept";
    type Params = crate::network::RemoveInterceptParameters;
    type Response = crate::network::RemoveInterceptResult;
}

/// `network.setCacheBehavior`
pub struct SetCacheBehavior;
impl crate::BidiCommand for SetCacheBehavior {
    const METHOD: &'static str = "network.setCacheBehavior";
    type Params = crate::network::SetCacheBehaviorParameters;
    type Response = crate::network::SetCacheBehaviorResult;
}

/// `network.setExtraHeaders`
pub struct SetExtraHeaders;
impl crate::BidiCommand for SetExtraHeaders {
    const METHOD: &'static str = "network.setExtraHeaders";
    type Params = crate::network::SetExtraHeadersParameters;
    type Response = crate::network::SetExtraHeadersResult;
}

/// `network.authRequired`
pub struct AuthRequired;
impl crate::BidiEvent for AuthRequired {
    const METHOD: &'static str = "network.authRequired";
    type Params = crate::network::AuthRequiredParameters;
}

