// @generated by scripts/generate_rust_code.py -- do not edit by hand.
//! Rust types for the [W3C WebDriver BiDi](https://w3c.github.io/webdriver-bidi/)
//! protocol. Generated from the specification's CDDL definitions.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;

/// A typed BiDi command: pairs a wire `method` with its params and result.
pub trait BidiCommand {
    const METHOD: &'static str;
    type Params: Serialize;
    type Response: for<'de> Deserialize<'de>;

    /// Build the outbound envelope for this command.
    fn command<'a>(id: u64, params: &'a Self::Params) -> Command<'a, Self>
    where
        Self: Sized,
    {
        Command { id, method: Self::METHOD, params }
    }
}

/// A typed BiDi event.
pub trait BidiEvent {
    const METHOD: &'static str;
    type Params: for<'de> Deserialize<'de>;
}

/// Outbound command envelope: `{ id, method, params }`.
#[derive(Serialize)]
pub struct Command<'a, T: BidiCommand> {
    pub id: u64,
    pub method: &'static str,
    pub params: &'a T::Params,
}

impl<'a, T: BidiCommand> Command<'a, T> {
    pub fn new(id: u64, params: &'a T::Params) -> Self {
        Self { id, method: T::METHOD, params }
    }
}

/// Successful reply: `{ id, type: "success", result }`.
#[derive(Deserialize, Debug, Clone)]
pub struct SuccessResponse<T> {
    pub id: u64,
    pub result: T,
}

/// Error reply: `{ id, type: "error", error, message, ? stacktrace }`.
#[derive(Deserialize, Debug, Clone)]
pub struct ErrorResponse {
    #[serde(default)]
    pub id: Option<u64>,
    pub error: String,
    pub message: String,
    #[serde(default)]
    pub stacktrace: Option<String>,
}

/// The `{}` result returned by commands with no typed result.
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
pub struct EmptyResult {}

/// The `{}` params object used by commands that take no parameters.
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
pub struct EmptyParams {}


pub mod browser;
pub mod browsing_context;
pub mod emulation;
pub mod input;
pub mod log;
pub mod network;
pub mod script;
pub mod session;
pub mod storage;
pub mod web_extension;

/// `ErrorCode`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ErrorCode {
    #[serde(rename = "invalid argument")]
    InvalidArgument,
    #[serde(rename = "invalid selector")]
    InvalidSelector,
    #[serde(rename = "invalid session id")]
    InvalidSessionId,
    #[serde(rename = "invalid web extension")]
    InvalidWebExtension,
    #[serde(rename = "move target out of bounds")]
    MoveTargetOutOfBounds,
    #[serde(rename = "no such alert")]
    NoSuchAlert,
    #[serde(rename = "no such network collector")]
    NoSuchNetworkCollector,
    #[serde(rename = "no such element")]
    NoSuchElement,
    #[serde(rename = "no such frame")]
    NoSuchFrame,
    #[serde(rename = "no such handle")]
    NoSuchHandle,
    #[serde(rename = "no such history entry")]
    NoSuchHistoryEntry,
    #[serde(rename = "no such intercept")]
    NoSuchIntercept,
    #[serde(rename = "no such network data")]
    NoSuchNetworkData,
    #[serde(rename = "no such node")]
    NoSuchNode,
    #[serde(rename = "no such request")]
    NoSuchRequest,
    #[serde(rename = "no such screencast")]
    NoSuchScreencast,
    #[serde(rename = "no such script")]
    NoSuchScript,
    #[serde(rename = "no such storage partition")]
    NoSuchStoragePartition,
    #[serde(rename = "no such user context")]
    NoSuchUserContext,
    #[serde(rename = "no such web extension")]
    NoSuchWebExtension,
    #[serde(rename = "session not created")]
    SessionNotCreated,
    #[serde(rename = "unable to capture screen")]
    UnableToCaptureScreen,
    #[serde(rename = "unable to close browser")]
    UnableToCloseBrowser,
    #[serde(rename = "unable to set cookie")]
    UnableToSetCookie,
    #[serde(rename = "unable to set file input")]
    UnableToSetFileInput,
    #[serde(rename = "unavailable network data")]
    UnavailableNetworkData,
    #[serde(rename = "underspecified storage partition")]
    UnderspecifiedStoragePartition,
    #[serde(rename = "unknown command")]
    UnknownCommand,
    #[serde(rename = "unknown error")]
    UnknownError,
    #[serde(rename = "unsupported operation")]
    UnsupportedOperation,
}

