"""Shared helpers for the per-language binding generators.

The workspace-level helpers (``ensure_rust_build``, ``copy_native_libs``, …) live
in ``scripts/common.py``; this module adds the Gradle scaffolding shared by the
JVM generators and re-exports everything so each generator needs a single import.

The generators live in ``scripts/generate_bindings/`` and are invoked directly,
so this module puts the parent ``scripts/`` directory on ``sys.path`` first.
"""

from __future__ import annotations

import os
import sys

# The workspace-level ``common`` module is one directory up from this package.
_SCRIPTS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

# Imported after the sys.path fix above so ``common`` resolves.
from common import (
    BINDINGS_DIR,
    BUILT_DLL,
    NATIVE_LIBS,
    ROOT,
    copy_native_libs,
    ensure_rust_build,
    find_binding_tool,
    find_tool,
    gradle_tool,
    jvm_env,
    log,
    run_checked,
    uniffi_bindgen,
    workspace_version,
    write_file,
)

__all__ = [
    "BINDINGS_DIR",
    "BUILT_DLL",
    "NATIVE_LIBS",
    "ROOT",
    "copy_native_libs",
    "ensure_rust_build",
    "find_binding_tool",
    "find_tool",
    "gradle_build_script",
    "gradle_tool",
    "jvm_env",
    "log",
    "run_checked",
    "uniffi_bindgen",
    "workspace_version",
    "write_file",
    "write_gradle_project",
]


# --------------------------------------------------------------------------- #
# Gradle project scaffolding (shared by the Java and Kotlin generators)
# --------------------------------------------------------------------------- #
GRADLE_SETTINGS = 'rootProject.name = "xcelerate"\n'
GRADLE_PROPERTIES = "org.gradle.jvmargs=-Xmx1g\norg.gradle.caching=true\n"
GRADLE_GITIGNORE = ".gradle/\n.kotlin/\nbuild/\n"

# A Gradle JVM library that publishes to Maven Central. Everything except the
# language-specific pieces (plugins, dependencies, compile options, coordinates)
# is identical between the Java and Kotlin bindings.
_GRADLE_BUILD = """\
// Generated by @GENERATOR@ - edit the script, not this.
plugins {
@PLUGINS@
}

group = "io.github.azzodude"
version = "@VERSION@"

repositories {
    mavenCentral()
}
@DEPENDENCIES@
java {
    withSourcesJar()
    withJavadocJar()
}

// Generated doc comments contain raw HTML (e.g. `<input>`), which the strict
// doclint checker rejects; disable it so the javadoc jar builds.
tasks.withType<Javadoc>().configureEach {
    (options as org.gradle.external.javadoc.StandardJavadocDocletOptions)
        .addBooleanOption("Xdoclint:none", true)
}
@COMPILE@
// Bundle the native core in the jar so consumers can extract it and point the
// loader at it with -Duniffi.component.xcelerate.libraryOverride=<abs path>.
tasks.processResources {
    from(rootDir) {
        include("*.dll", "*.so", "*.dylib")
        into("uniffi/xcelerate")
    }
}

// Resolve credentials from (in order) a -P/Gradle property, an environment
// variable, then the nearest .env file. Never commit real secrets.
val dotenv: Map<String, String> = generateSequence(projectDir) { it.parentFile }
    .map { it.resolve(".env") }
    .firstOrNull { it.isFile }
    ?.readLines()
    ?.mapNotNull { line ->
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed.startsWith("#") || !trimmed.contains("=")) null
        else trimmed.substringBefore("=").trim() to trimmed.substringAfter("=").trim().trim('"')
    }?.toMap() ?: emptyMap()

fun secret(name: String): String? =
    providers.gradleProperty(name).orNull
        ?: providers.environmentVariable(name).orNull
        ?: dotenv[name]

signing {
    val inline = secret("signingKey")
    val keyFile = secret("signingKeyFile")
    val password = secret("signingPassword")
    when {
        inline != null && password != null -> useInMemoryPgpKeys(inline, password)
        keyFile != null && password != null -> useInMemoryPgpKeys(file(keyFile).readText(), password)
        else -> useGpgCmd()
    }
    sign(publishing.publications)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "@ARTIFACT@"
            pom {
                name.set("@POM_NAME@")
                description.set("@POM_DESCRIPTION@")
                url.set("https://github.com/AzzoDude/xcelerate")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("AzzoDude")
                        url.set("https://github.com/AzzoDude")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/AzzoDude/xcelerate.git")
                    developerConnection.set("scm:git:ssh://git@github.com/AzzoDude/xcelerate.git")
                    url.set("https://github.com/AzzoDude/xcelerate")
                }
            }
        }
    }
    repositories {
        maven {
            name = "central"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
            credentials {
                username = secret("centralUsername")
                password = secret("centralPassword")
            }
        }
    }
}
"""


def gradle_build_script(
    generator,
    *,
    plugins,
    artifact,
    pom_name,
    pom_description,
    dependencies="",
    compile_options="",
):
    """Render the shared ``build.gradle.kts`` for a JVM binding.

    ``plugins``, ``dependencies`` and ``compile_options`` are pre-formatted
    blocks (or empty); ``generator`` is the script path embedded in the header.
    """
    return (
        _GRADLE_BUILD.replace("@GENERATOR@", generator)
        .replace("@PLUGINS@", plugins)
        .replace("@VERSION@", workspace_version())
        .replace("@DEPENDENCIES@", dependencies)
        .replace("@COMPILE@", compile_options)
        .replace("@ARTIFACT@", artifact)
        .replace("@POM_NAME@", pom_name)
        .replace("@POM_DESCRIPTION@", pom_description)
    )


def write_gradle_project(directory, build_gradle):
    """Write the standard Gradle project files plus the given build script."""
    write_file(os.path.join(directory, "settings.gradle.kts"), GRADLE_SETTINGS)
    write_file(os.path.join(directory, "gradle.properties"), GRADLE_PROPERTIES)
    write_file(os.path.join(directory, ".gitignore"), GRADLE_GITIGNORE)
    write_file(os.path.join(directory, "build.gradle.kts"), build_gradle)
