#!/usr/bin/env python3
"""Generate the Dart/Flutter bindings and assemble a pub package.

Dart is not a built-in UniFFI target; it needs the external
``uniffi-bindgen-dart`` generator (``cargo install uniffi-bindgen-dart``). The
generator emits a single ``xcelerate.dart`` which loads the native library named
``uniffi_xcelerate`` (``uniffi_xcelerate.dll`` / ``libuniffi_xcelerate.so`` /
``libuniffi_xcelerate.dylib``); this script places it under ``lib/``, writes a
``pubspec.yaml``, and copies the native library under that name.

Building/analyzing needs the Dart SDK (``dart``/``flutter`` on ``PATH``); the
script skips with a hint if it is missing.
"""

from __future__ import annotations

import os
import re
import subprocess

try:
    from ._shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_binding_tool,
        find_tool,
        log,
        run_checked,
        workspace_version,
        write_file,
    )
except ImportError:  # pragma: no cover - executed as a standalone script
    from _shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_binding_tool,
        find_tool,
        log,
        run_checked,
        workspace_version,
        write_file,
    )

# (source name in target/release, destination name for Dart FFI)
NATIVE_LIBS = (
    ("xcelerate.dll", "uniffi_xcelerate.dll"),
    ("libxcelerate.so", "libuniffi_xcelerate.so"),
    ("libxcelerate.dylib", "libuniffi_xcelerate.dylib"),
)


def pubspec(version: str) -> str:
    return f"""\
# Generated by scripts/generate_bindings/dart.py - edit the script, not this.
name: xcelerate
description: Chrome DevTools Protocol client for Dart/Flutter, backed by the xcelerate Rust core.
version: {version}
homepage: https://github.com/AzzoDude/xcelerate
repository: https://github.com/AzzoDude/xcelerate
environment:
  sdk: ">=3.1.0 <4.0.0"
dependencies:
  ffi: ^2.1.0
"""


def dart_exe() -> str:
    """Locate `dart`, normalising an uppercase `.EXE` suffix.

    `dartdev` appends `.exe` to the running executable to spawn its analysis
    server, but its suffix check is case-sensitive, so `dart.EXE` becomes
    `dart.EXE.exe` and the process fails. Lower-casing the suffix avoids it.
    """
    found = find_tool("dart")
    if found.lower().endswith(".exe"):
        return found[:-4] + ".exe"
    return found


# ---------------------------------------------------------------------------
# Post-processing for known uniffi-bindgen-dart 0.1.x codegen bugs
# ---------------------------------------------------------------------------
#
# The early generator emits invalid Dart for this API in three ways. Each fix is
# a narrowly-scoped rewrite of the generated file; regenerate to reproduce.
#
#   1. `Future<bool>` methods that call an `i8` future-complete return the raw
#      `int`, not a `bool`.
#   2. The async constructor `Browser::launch` is emitted as a synchronous
#      return, but declared `Future<Browser>`.
#   3. `Browser::close` / `Page::close` collide with the generator's synthetic
#      `close()` disposer, so they are renamed `closeBrowser` / `closePage`
#      (matching the Kotlin binding).

_BOOL_RETURN = re.compile(
    r"(Future<bool> \w+\([^)]*\) async \{.*?)return resultValue;", re.DOTALL
)
_LAUNCH = re.compile(r"static Future<Browser> launch\(BrowserConfig config\) \{")
_CLOSE = re.compile(
    r"Future<void> close\(\)(?=.{0,400}?\b(?P<call>browserInvokeClose|pageInvokeClose)\b)",
    re.DOTALL,
)


def _patch(content: str) -> tuple[str, dict[str, int]]:
    counts: dict[str, int] = {}

    content, counts["bool futures"] = _BOOL_RETURN.subn(
        r"\1return resultValue != 0;", content
    )
    content, counts["launch async"] = _LAUNCH.subn(
        "static Future<Browser> launch(BrowserConfig config) async {", content
    )

    def rename_close(match: re.Match) -> str:
        if match.group("call") == "browserInvokeClose":
            return "Future<void> closeBrowser()"
        return "Future<void> closePage()"

    content, counts["close rename"] = _CLOSE.subn(rename_close, content)
    return content, counts


def main():
    dart_dir = os.path.join(ROOT, "bindings", "dart")
    lib_dir = os.path.join(dart_dir, "lib")
    src_dir = os.path.join(dart_dir, "src")

    print("--- Phase: Generating Dart Bindings ---")
    os.makedirs(lib_dir, exist_ok=True)
    os.makedirs(src_dir, exist_ok=True)

    tool = find_binding_tool(
        "uniffi-bindgen-dart", "run `cargo install uniffi-bindgen-dart` to install it"
    )
    if not tool:
        return 0

    ensure_rust_build()

    print("--- 1. Generating Dart sources ---")
    stale = os.path.join(lib_dir, "xcelerate.dart")
    if os.path.exists(stale):
        os.remove(stale)
    run_checked(
        [tool, "generate", "--out-dir", lib_dir, "--no-format", BUILT_DLL],
        cwd=ROOT,
    )

    print("--- 1b. Patching known generator bugs ---")
    generated = os.path.join(lib_dir, "xcelerate.dart")
    with open(generated, "r", encoding="utf-8") as handle:
        content = handle.read()
    content, fixes = _patch(content)
    with open(generated, "w", encoding="utf-8", newline="") as handle:
        handle.write(content)
    for fix, count in fixes.items():
        level = "PATCH" if count else "WARNING"
        log(level, f"{fix}: {count}")

    write_file(os.path.join(dart_dir, "pubspec.yaml"), pubspec(workspace_version()))
    log("WRITE", "pubspec.yaml")

    print("--- 2. Distributing native libraries ---")
    copy_native_libs(src_dir, NATIVE_LIBS)

    print("--- 3. Fetching deps and analyzing ---")
    dart = dart_exe()
    if not os.path.exists(dart):
        log("WARNING", "dart not found; sources generated only")
        log("HINT", "install the Dart SDK or Flutter (dart.dev)")
        return 0
    # Run dart directly (not through a shell); shell=True breaks `dart analyze`
    # on Windows.
    get = subprocess.run(
        [dart, "pub", "get"], cwd=dart_dir, capture_output=True, text=True, check=False
    )
    if get.returncode != 0:
        log("WARNING", "`dart pub get` failed; skipping analysis")
        return 0
    analyze = subprocess.run(
        [dart, "analyze"], cwd=dart_dir, capture_output=True, text=True, check=False
    )
    output = (analyze.stdout or "") + (analyze.stderr or "")
    if analyze.returncode == 0 or "No issues found" in output:
        log("OK", "dart analyze: no issues")
    else:
        log("WARNING", "`dart analyze` reported issues; check bindings/dart")
    log("SUCCESS", f"Dart bindings ready in {dart_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
