#!/usr/bin/env python3
"""Generate the Go bindings and assemble a Go module.

Go is not a built-in UniFFI target. It needs the external
``uniffi-bindgen-go`` generator, which is **not** on crates.io - install it with
the Go toolchain:

    go install github.com/NordSecurity/uniffi-bindgen-go/v2/uniffi-bindgen-go@latest

The generator emits a Go package that cgo-links the native library. This script
runs it, copies the native library for the host platform, and writes a ``go.mod``.

Building needs the Go toolchain (``go`` on ``PATH``); the script skips with a
hint if either the generator or Go is missing.
"""

from __future__ import annotations

import os

try:
    from ._shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_binding_tool,
        find_tool,
        log,
        run_checked,
        write_file,
    )
except ImportError:  # pragma: no cover - executed as a standalone script
    from _shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_binding_tool,
        find_tool,
        log,
        run_checked,
        write_file,
    )

GO_MOD = """\
// Generated by scripts/generate_bindings/go.py - edit the script, not this.
//
// The module lives in `bindings/go`, so the path must be repo + subdir and the
// release tag must be `bindings/go/vX.Y.Z`.
module github.com/AzzoDude/xcelerate/bindings/go

go 1.21
"""


def main():
    go_dir = os.path.join(ROOT, "bindings", "go")

    print("--- Phase: Generating Go Bindings ---")
    os.makedirs(go_dir, exist_ok=True)

    tool = find_binding_tool(
        "uniffi-bindgen-go",
        "run `go install github.com/NordSecurity/uniffi-bindgen-go/v2/uniffi-bindgen-go@latest`",
    )
    if not tool:
        return 0

    ensure_rust_build()

    print("--- 1. Generating Go sources ---")
    run_checked(
        [tool, BUILT_DLL, "--out-dir", go_dir, "--no-format"],
        cwd=ROOT,
    )

    write_file(os.path.join(go_dir, "go.mod"), GO_MOD)
    log("WRITE", "go.mod")

    print("--- 2. Distributing native libraries ---")
    copy_native_libs(go_dir)

    print("--- 3. Building the Go package ---")
    go = find_tool("go")
    if not os.path.exists(go):
        log("WARNING", "go not found; sources generated only")
        log("HINT", "install the Go toolchain (go.dev/dl)")
        return 0
    run_checked([go, "build", "./..."], cwd=go_dir)
    log("SUCCESS", f"Go bindings ready in {go_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
