#!/usr/bin/env python3
"""Generate the Ruby bindings (uniffi) and assemble a gem.

Ruby is a built-in UniFFI target. The generator emits a single ``xcelerate.rb``;
this script places it under ``lib/`` (the conventional gem layout), writes a
gemspec, and copies the native library for the host platform.

Building/pushing the gem needs Ruby (``ruby``/``gem`` on ``PATH``); the script
skips the build with a hint if it is missing.
"""

from __future__ import annotations

import os

try:
    from ._shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_tool,
        log,
        run_checked,
        uniffi_bindgen,
        workspace_version,
        write_file,
    )
except ImportError:  # pragma: no cover - executed as a standalone script
    from _shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_tool,
        log,
        run_checked,
        uniffi_bindgen,
        workspace_version,
        write_file,
    )

GEMSPEC = """\
# Generated by scripts/generate_bindings/ruby.py - edit the script, not this.
Gem::Specification.new do |spec|
  spec.name          = "xcelerate"
  spec.version       = "@VERSION@"
  spec.summary       = "Chrome DevTools Protocol client for Ruby (xcelerate core)."
  spec.description   = "Ruby bindings for the xcelerate CDP engine, generated with UniFFI."
  spec.authors       = ["AzzoDude"]
  spec.homepage      = "https://github.com/AzzoDude/xcelerate"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.1"

  spec.files = Dir["lib/**/*.rb", "*.dll", "*.so", "*.dylib"]
  spec.require_paths = ["lib"]
  spec.add_dependency "ffi", "~> 1.15"
end
"""


def main():
    ruby_dir = os.path.join(ROOT, "bindings", "ruby")
    lib_dir = os.path.join(ruby_dir, "lib")

    print("--- Phase: Generating Ruby Bindings ---")
    os.makedirs(lib_dir, exist_ok=True)

    ensure_rust_build()

    print("--- 1. Generating Ruby sources with UniFFI ---")
    stale = os.path.join(lib_dir, "xcelerate.rb")
    if os.path.exists(stale):
        os.remove(stale)
    run_checked(
        uniffi_bindgen()
        + [
            "generate",
            "--library",
            BUILT_DLL,
            "--language",
            "ruby",
            "--out-dir",
            lib_dir,
            "--no-format",
        ],
        cwd=ROOT,
    )

    write_file(
        os.path.join(ruby_dir, "xcelerate.gemspec"),
        GEMSPEC.replace("@VERSION@", workspace_version()),
    )
    log("WRITE", "xcelerate.gemspec")

    print("--- 2. Distributing native libraries ---")
    copy_native_libs(ruby_dir)

    print("--- 3. Validating the gem ---")
    ruby = find_tool("ruby")
    if not os.path.exists(ruby):
        log("WARNING", "ruby not found; sources generated only")
        log("HINT", "install Ruby 3.1+ (ruby-lang.org or your package manager)")
        return 0
    run_checked([ruby, "-c", os.path.join(lib_dir, "xcelerate.rb")])
    log("SUCCESS", f"Ruby bindings ready in {ruby_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
