#!/usr/bin/env python3
"""Generate the Swift bindings (uniffi) and assemble a SwiftPM package.

Swift is a built-in UniFFI target. The generator emits a Swift module plus a C
header/modulemap for the low-level FFI; this script arranges them into a SwiftPM
package layout (``Sources/Xcelerate`` + ``Sources/xcelerateFFI``) and copies the
native library for the host platform.

Building the package needs a Swift toolchain (``swift`` on ``PATH``); the script
skips the build with a hint if it is missing.
"""

from __future__ import annotations

import os
import shutil

try:
    from ._shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_tool,
        log,
        run_checked,
        uniffi_bindgen,
        write_file,
    )
except ImportError:  # pragma: no cover - executed as a standalone script
    from _shared import (
        BUILT_DLL,
        ROOT,
        copy_native_libs,
        ensure_rust_build,
        find_tool,
        log,
        run_checked,
        uniffi_bindgen,
        write_file,
    )

PACKAGE_SWIFT = """\
// swift-tools-version:5.9
// Generated by scripts/generate_bindings/swift.py - edit the script, not this.
import PackageDescription

let package = Package(
    name: "Xcelerate",
    platforms: [.macOS(.v12)],
    products: [
        .library(name: "Xcelerate", targets: ["Xcelerate"]),
    ],
    targets: [
        // The generated C header + modulemap for the low-level FFI.
        .systemLibrary(name: "xcelerateFFI", path: "Sources/xcelerateFFI"),
        // The generated Swift API.
        .target(
            name: "Xcelerate",
            dependencies: ["xcelerateFFI"],
            path: "Sources/Xcelerate"
        ),
    ]
)
"""


def main():
    swift_dir = os.path.join(ROOT, "bindings", "swift")
    api_dir = os.path.join(swift_dir, "Sources", "Xcelerate")
    ffi_dir = os.path.join(swift_dir, "Sources", "xcelerateFFI")

    print("--- Phase: Generating Swift Bindings ---")

    ensure_rust_build()

    # Regenerate from scratch but never delete hand-authored package metadata.
    for directory in (api_dir, ffi_dir):
        if os.path.isdir(directory):
            shutil.rmtree(directory)
        os.makedirs(directory, exist_ok=True)

    print("--- 1. Generating Swift sources with UniFFI ---")
    run_checked(
        uniffi_bindgen()
        + [
            "generate",
            "--library",
            BUILT_DLL,
            "--language",
            "swift",
            "--out-dir",
            swift_dir,
            "--no-format",
        ],
        cwd=ROOT,
    )

    # Arrange the generated files into the package layout.
    generated_api = os.path.join(swift_dir, "xcelerate.swift")
    header = os.path.join(swift_dir, "xcelerateFFI.h")
    modulemap = os.path.join(swift_dir, "xcelerateFFI.modulemap")
    if os.path.exists(generated_api):
        shutil.move(generated_api, os.path.join(api_dir, "xcelerate.swift"))
    if os.path.exists(header):
        shutil.move(header, os.path.join(ffi_dir, "xcelerateFFI.h"))
    if os.path.exists(modulemap):
        # SwiftPM's systemLibrary target expects `module.modulemap`.
        shutil.move(modulemap, os.path.join(ffi_dir, "module.modulemap"))

    write_file(os.path.join(swift_dir, "Package.swift"), PACKAGE_SWIFT)
    log("WRITE", "Package.swift")

    print("--- 2. Distributing native libraries ---")
    copy_native_libs(swift_dir)

    print("--- 3. Building Swift package ---")
    swift = find_tool("swift")
    if not os.path.exists(swift):
        log("WARNING", "swift not found; sources generated only")
        log("HINT", "install the Swift toolchain (macOS: Xcode, Windows/Linux: swift.org)")
        return 0
    run_checked([swift, "build"], cwd=swift_dir)
    log("SUCCESS", f"Swift bindings ready in {swift_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
