// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `storage.BrowsingContextPartitionDescriptor`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BrowsingContextPartitionDescriptor {
    #[serde(rename = "type")]
    pub type_: String,
    pub context: crate::browsing_context::BrowsingContext,
}

/// `storage.CookieFilter`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CookieFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::network::BytesValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub domain: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub size: Option<u64>,
    #[serde(rename = "httpOnly", skip_serializing_if = "Option::is_none")]
    pub http_only: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    #[serde(rename = "sameSite", skip_serializing_if = "Option::is_none")]
    pub same_site: Option<crate::network::SameSite>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry: Option<u64>,
}

/// `storage.DeleteCookiesParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DeleteCookiesParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filter: Option<crate::storage::CookieFilter>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub partition: Option<crate::storage::PartitionDescriptor>,
}

/// `storage.DeleteCookiesResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DeleteCookiesResult {
    #[serde(rename = "partitionKey")]
    pub partition_key: crate::storage::PartitionKey,
}

/// `storage.GetCookiesParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetCookiesParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub filter: Option<crate::storage::CookieFilter>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub partition: Option<crate::storage::PartitionDescriptor>,
}

/// `storage.GetCookiesResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetCookiesResult {
    pub cookies: Vec<crate::network::Cookie>,
    #[serde(rename = "partitionKey")]
    pub partition_key: crate::storage::PartitionKey,
}

/// `storage.PartialCookie`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PartialCookie {
    pub name: String,
    pub value: crate::network::BytesValue,
    pub domain: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    #[serde(rename = "httpOnly", skip_serializing_if = "Option::is_none")]
    pub http_only: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub secure: Option<bool>,
    #[serde(rename = "sameSite", skip_serializing_if = "Option::is_none")]
    pub same_site: Option<crate::network::SameSite>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub expiry: Option<u64>,
}

/// `storage.PartitionDescriptor`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum PartitionDescriptor {
    BrowsingContextPartitionDescriptor(crate::storage::BrowsingContextPartitionDescriptor),
    StorageKeyPartitionDescriptor(crate::storage::StorageKeyPartitionDescriptor),
}

/// `storage.PartitionKey`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PartitionKey {
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<String>,
    #[serde(rename = "sourceOrigin", skip_serializing_if = "Option::is_none")]
    pub source_origin: Option<String>,
}

/// `storage.SetCookieParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetCookieParameters {
    pub cookie: crate::storage::PartialCookie,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub partition: Option<crate::storage::PartitionDescriptor>,
}

/// `storage.SetCookieResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetCookieResult {
    #[serde(rename = "partitionKey")]
    pub partition_key: crate::storage::PartitionKey,
}

/// `storage.StorageKeyPartitionDescriptor`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StorageKeyPartitionDescriptor {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<String>,
    #[serde(rename = "sourceOrigin", skip_serializing_if = "Option::is_none")]
    pub source_origin: Option<String>,
}

/// `storage.deleteCookies`
pub struct DeleteCookies;
impl crate::BidiCommand for DeleteCookies {
    const METHOD: &'static str = "storage.deleteCookies";
    type Params = crate::storage::DeleteCookiesParameters;
    type Response = crate::storage::DeleteCookiesResult;
}

/// `storage.getCookies`
pub struct GetCookies;
impl crate::BidiCommand for GetCookies {
    const METHOD: &'static str = "storage.getCookies";
    type Params = crate::storage::GetCookiesParameters;
    type Response = crate::storage::GetCookiesResult;
}

/// `storage.setCookie`
pub struct SetCookie;
impl crate::BidiCommand for SetCookie {
    const METHOD: &'static str = "storage.setCookie";
    type Params = crate::storage::SetCookieParameters;
    type Response = crate::storage::SetCookieResult;
}

