// Generated by scripts/generate_kotlin_bindings.py - edit the script, not this.
plugins {
    kotlin("jvm") version "2.1.0"
    `java-library`
    `maven-publish`
    `signing`
}

group = "io.github.azzodude"
version = "1.0.9"

repositories {
    mavenCentral()
}

dependencies {
    // The generated bindings use JNA for the FFI and kotlinx-coroutines for the
    // suspend/asynchronous API surface.
    api("net.java.dev.jna:jna:5.16.0")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1")
}

java {
    withSourcesJar()
    withJavadocJar()
}

// Generated doc comments contain raw HTML (e.g. `<input>`), which the strict
// doclint checker rejects; disable it so the javadoc jar builds.
tasks.withType<Javadoc>().configureEach {
    (options as org.gradle.external.javadoc.StandardJavadocDocletOptions)
        .addBooleanOption("Xdoclint:none", true)
}

// Bundle the native core in the jar so consumers can extract it and point the
// loader at it with -Duniffi.component.xcelerate.libraryOverride=<abs path>.
tasks.processResources {
    from(rootDir) {
        include("*.dll", "*.so", "*.dylib")
        into("uniffi/xcelerate")
    }
}

// Resolve credentials from (in order) a -P/Gradle property, an environment
// variable, then the nearest .env file. Never commit real secrets.
val dotenv: Map<String, String> = generateSequence(projectDir) { it.parentFile }
    .map { it.resolve(".env") }
    .firstOrNull { it.isFile }
    ?.readLines()
    ?.mapNotNull { line ->
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed.startsWith("#") || !trimmed.contains("=")) null
        else trimmed.substringBefore("=").trim() to trimmed.substringAfter("=").trim().trim('"')
    }?.toMap() ?: emptyMap()

fun secret(name: String): String? =
    providers.gradleProperty(name).orNull
        ?: providers.environmentVariable(name).orNull
        ?: dotenv[name]

signing {
    val inline = secret("signingKey")
    val keyFile = secret("signingKeyFile")
    val password = secret("signingPassword")
    when {
        inline != null && password != null -> useInMemoryPgpKeys(inline, password)
        keyFile != null && password != null -> useInMemoryPgpKeys(file(keyFile).readText(), password)
        else -> useGpgCmd()
    }
    sign(publishing.publications)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "xcelerate"
            pom {
                name.set("Xcelerate Kotlin SDK")
                description.set("Kotlin/JVM bindings for the xcelerate CDP engine.")
                url.set("https://github.com/AzzoDude/xcelerate")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("AzzoDude")
                        url.set("https://github.com/AzzoDude")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/AzzoDude/xcelerate.git")
                    developerConnection.set("scm:git:ssh://git@github.com/AzzoDude/xcelerate.git")
                    url.set("https://github.com/AzzoDude/xcelerate")
                }
            }
        }
    }
    repositories {
        maven {
            name = "central"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
            credentials {
                username = secret("centralUsername")
                password = secret("centralPassword")
            }
        }
    }
}
