[package]
name = "xcelerate-plugin-human"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "The human plugin for xcelerate: human-like mouse, typing, and scrolling."

[dependencies]
xcelerate-plugin = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
