// Generated by scripts/generate_go_bindings.py - edit the script, not this.
//
// The module lives in `bindings/go`, so the path must be repo + subdir and the
// release tag must be `bindings/go/vX.Y.Z`.
module github.com/AzzoDude/xcelerate/bindings/go

go 1.21
