// swift-tools-version:5.9
// Generated by scripts/generate_bindings/swift.py - edit the script, not this.
import PackageDescription

let package = Package(
    name: "Xcelerate",
    platforms: [.macOS(.v12)],
    products: [
        .library(name: "Xcelerate", targets: ["Xcelerate"]),
    ],
    targets: [
        // The generated C header + modulemap for the low-level FFI.
        .systemLibrary(name: "xcelerateFFI", path: "Sources/xcelerateFFI"),
        // The generated Swift API.
        .target(
            name: "Xcelerate",
            dependencies: ["xcelerateFFI"],
            path: "Sources/Xcelerate"
        ),
    ]
)
