// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `session.AutodetectProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AutodetectProxyConfiguration {
    #[serde(rename = "proxyType")]
    pub proxy_type: String,
}

/// `session.CapabilitiesRequest`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CapabilitiesRequest {
    #[serde(rename = "alwaysMatch", skip_serializing_if = "Option::is_none")]
    pub always_match: Option<crate::session::CapabilityRequest>,
    #[serde(rename = "firstMatch", skip_serializing_if = "Option::is_none")]
    pub first_match: Option<Vec<crate::session::CapabilityRequest>>,
}

/// `session.CapabilityRequest`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CapabilityRequest {
    #[serde(rename = "acceptInsecureCerts", skip_serializing_if = "Option::is_none")]
    pub accept_insecure_certs: Option<bool>,
    #[serde(rename = "browserName", skip_serializing_if = "Option::is_none")]
    pub browser_name: Option<String>,
    #[serde(rename = "browserVersion", skip_serializing_if = "Option::is_none")]
    pub browser_version: Option<String>,
    #[serde(rename = "platformName", skip_serializing_if = "Option::is_none")]
    pub platform_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<crate::session::ProxyConfiguration>,
    #[serde(rename = "unhandledPromptBehavior", skip_serializing_if = "Option::is_none")]
    pub unhandled_prompt_behavior: Option<crate::session::UserPromptHandler>,
}

/// `session.CapabilityResponse`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CapabilityResponse {
    #[serde(rename = "acceptInsecureCerts")]
    pub accept_insecure_certs: bool,
    #[serde(rename = "browserName")]
    pub browser_name: String,
    #[serde(rename = "browserVersion")]
    pub browser_version: String,
    #[serde(rename = "platformName")]
    pub platform_name: String,
    #[serde(rename = "setWindowRect")]
    pub set_window_rect: bool,
    #[serde(rename = "userAgent")]
    pub user_agent: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<crate::session::ProxyConfiguration>,
    #[serde(rename = "unhandledPromptBehavior", skip_serializing_if = "Option::is_none")]
    pub unhandled_prompt_behavior: Option<crate::session::UserPromptHandler>,
    #[serde(rename = "webSocketUrl", skip_serializing_if = "Option::is_none")]
    pub web_socket_url: Option<String>,
}

/// `session.DirectProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DirectProxyConfiguration {
    #[serde(rename = "proxyType")]
    pub proxy_type: String,
}

/// `session.EndResult`
pub type EndResult = crate::EmptyResult;

/// `session.ManualProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ManualProxyConfiguration {
    #[serde(rename = "proxyType")]
    pub proxy_type: String,
    #[serde(rename = "httpProxy", skip_serializing_if = "Option::is_none")]
    pub http_proxy: Option<String>,
    #[serde(rename = "sslProxy", skip_serializing_if = "Option::is_none")]
    pub ssl_proxy: Option<String>,
    #[serde(flatten)]
    pub socks_proxy_configuration: crate::session::SocksProxyConfiguration,
    #[serde(rename = "noProxy", skip_serializing_if = "Option::is_none")]
    pub no_proxy: Option<Vec<String>>,
}

/// `session.NewParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NewParameters {
    pub capabilities: crate::session::CapabilitiesRequest,
}

/// `session.NewResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NewResult {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    pub capabilities: crate::session::CapabilityResponse,
}

/// `session.PacProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PacProxyConfiguration {
    #[serde(rename = "proxyType")]
    pub proxy_type: String,
    #[serde(rename = "proxyAutoconfigUrl")]
    pub proxy_autoconfig_url: String,
}

/// `session.ProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ProxyConfiguration {
    AutodetectProxyConfiguration(crate::session::AutodetectProxyConfiguration),
    DirectProxyConfiguration(crate::session::DirectProxyConfiguration),
    ManualProxyConfiguration(crate::session::ManualProxyConfiguration),
    PacProxyConfiguration(crate::session::PacProxyConfiguration),
    SystemProxyConfiguration(crate::session::SystemProxyConfiguration),
}

/// `session.SocksProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SocksProxyConfiguration {
    #[serde(rename = "socksProxy")]
    pub socks_proxy: String,
    #[serde(rename = "socksVersion")]
    pub socks_version: u64,
}

/// `session.StatusResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StatusResult {
    pub ready: bool,
    pub message: String,
}

/// `session.SubscribeParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SubscribeParameters {
    pub events: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `session.SubscribeResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SubscribeResult {
    pub subscription: crate::session::Subscription,
}

/// `session.Subscription`
pub type Subscription = String;

/// `session.SystemProxyConfiguration`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SystemProxyConfiguration {
    #[serde(rename = "proxyType")]
    pub proxy_type: String,
}

/// `session.UnsubscribeByAttributesRequest`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UnsubscribeByAttributesRequest {
    pub events: Vec<String>,
}

/// `session.UnsubscribeByIDRequest`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UnsubscribeByIDRequest {
    pub subscriptions: Vec<crate::session::Subscription>,
}

/// `session.UnsubscribeParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum UnsubscribeParameters {
    UnsubscribeByAttributesRequest(crate::session::UnsubscribeByAttributesRequest),
    UnsubscribeByIDRequest(crate::session::UnsubscribeByIDRequest),
}

/// `session.UnsubscribeResult`
pub type UnsubscribeResult = crate::EmptyResult;

/// `session.UserPromptHandler`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UserPromptHandler {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alert: Option<crate::session::UserPromptHandlerType>,
    #[serde(rename = "beforeUnload", skip_serializing_if = "Option::is_none")]
    pub before_unload: Option<crate::session::UserPromptHandlerType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub confirm: Option<crate::session::UserPromptHandlerType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<crate::session::UserPromptHandlerType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file: Option<crate::session::UserPromptHandlerType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prompt: Option<crate::session::UserPromptHandlerType>,
}

/// `session.UserPromptHandlerType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum UserPromptHandlerType {
    #[serde(rename = "accept")]
    Accept,
    #[serde(rename = "dismiss")]
    Dismiss,
    #[serde(rename = "ignore")]
    Ignore,
}

/// `session.end`
pub struct End;
impl crate::BidiCommand for End {
    const METHOD: &'static str = "session.end";
    type Params = crate::EmptyParams;
    type Response = crate::session::EndResult;
}

/// `session.new`
pub struct New;
impl crate::BidiCommand for New {
    const METHOD: &'static str = "session.new";
    type Params = crate::session::NewParameters;
    type Response = crate::session::NewResult;
}

/// `session.status`
pub struct Status;
impl crate::BidiCommand for Status {
    const METHOD: &'static str = "session.status";
    type Params = crate::EmptyParams;
    type Response = crate::session::StatusResult;
}

/// `session.subscribe`
pub struct Subscribe;
impl crate::BidiCommand for Subscribe {
    const METHOD: &'static str = "session.subscribe";
    type Params = crate::session::SubscribeParameters;
    type Response = crate::session::SubscribeResult;
}

/// `session.unsubscribe`
pub struct Unsubscribe;
impl crate::BidiCommand for Unsubscribe {
    const METHOD: &'static str = "session.unsubscribe";
    type Params = crate::session::UnsubscribeParameters;
    type Response = crate::session::UnsubscribeResult;
}

