#!/usr/bin/env python3
"""Generate Rust types for the W3C WebDriver BiDi protocol.

Mirrors the `browser-protocol` generator's pipeline, but the harvest source is
different: Chrome DevTools Protocol ships a machine-readable JSON from Google
(`browser_protocol.json` / `js_protocol.json`), whereas WebDriver BiDi only ships
its definitions as *CDDL* embedded in the Bikeshed specification (`index.bs`).

Pipeline
--------
1. Download `index.bs` from the w3c/webdriver-bidi repository (or read a local
   copy with ``--spec``).
2. Extract every ``<pre class="cddl ...">`` block and concatenate them into a
   single ``all.cddl`` document (this is exactly what the W3C's own
   ``scripts/cddl/generate.js`` does, and what Google feeds to ``cddlconv`` to
   produce ``webdriver-bidi-protocol``).
3. Parse the CDDL into a small AST of definitions.
4. Emit one Rust module per BiDi module (``browsingContext`` -> ``browsing_context``)
   plus the root envelope in ``src/lib.rs``.

Usage
-----
    python scripts/generate_rust_code.py            # download + generate
    python scripts/generate_rust_code.py --spec path/to/index.bs
    python scripts/generate_rust_code.py --check     # exit 1 if the spec changed
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import urllib.request

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
SRC = os.path.join(ROOT, "src")

SPEC_URL = "https://raw.githubusercontent.com/w3c/webdriver-bidi/main/index.bs"
SPEC_FILE = os.path.join(ROOT, "webdriver_bidi.bs")
CDDL_FILE = os.path.join(ROOT, "all.cddl")

# CDDL primitives / builtins -> Rust types.
PRIMS = {
    "text": "String",
    "int": "i64",
    "js-int": "i64",
    "js-uint": "u64",
    "uint": "u64",
    "float": "f64",
    "number": "f64",
    "bool": "bool",
    "any": "JsonValue",
    "null": "JsonValue",
}

# Root definitions we hand-write (the wire envelope) or that only exist to
# drive dispatch, so we do not re-generate them.
SKIP_ROOT = {
    "Command", "CommandData", "CommandResponse", "ErrorResponse", "Message",
    "ResultData", "Event", "EventData", "EmptyParams", "EmptyResult",
    "Extensible", "js-int", "js-uint",
}

# Modules whose names are not a single lowercase word.
MODULE_NAMES = {
    "browsingContext": "browsing_context",
    "webExtension": "web_extension",
}

PROLOGUE = '''// @generated by scripts/generate_rust_code.py -- do not edit by hand.
//! Rust types for the [W3C WebDriver BiDi](https://w3c.github.io/webdriver-bidi/)
//! protocol. Generated from the specification's CDDL definitions.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;

/// A typed BiDi command: pairs a wire `method` with its params and result.
pub trait BidiCommand {
    const METHOD: &'static str;
    type Params: Serialize;
    type Response: for<'de> Deserialize<'de>;

    /// Build the outbound envelope for this command.
    fn command<'a>(id: u64, params: &'a Self::Params) -> Command<'a, Self>
    where
        Self: Sized,
    {
        Command { id, method: Self::METHOD, params }
    }
}

/// A typed BiDi event.
pub trait BidiEvent {
    const METHOD: &'static str;
    type Params: for<'de> Deserialize<'de>;
}

/// Outbound command envelope: `{ id, method, params }`.
#[derive(Serialize)]
pub struct Command<'a, T: BidiCommand> {
    pub id: u64,
    pub method: &'static str,
    pub params: &'a T::Params,
}

impl<'a, T: BidiCommand> Command<'a, T> {
    pub fn new(id: u64, params: &'a T::Params) -> Self {
        Self { id, method: T::METHOD, params }
    }
}

/// Successful reply: `{ id, type: "success", result }`.
#[derive(Deserialize, Debug, Clone)]
pub struct SuccessResponse<T> {
    pub id: u64,
    pub result: T,
}

/// Error reply: `{ id, type: "error", error, message, ? stacktrace }`.
#[derive(Deserialize, Debug, Clone)]
pub struct ErrorResponse {
    #[serde(default)]
    pub id: Option<u64>,
    pub error: String,
    pub message: String,
    #[serde(default)]
    pub stacktrace: Option<String>,
}

/// The `{}` result returned by commands with no typed result.
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
pub struct EmptyResult {}

/// The `{}` params object used by commands that take no parameters.
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq)]
pub struct EmptyParams {}
'''


# ---------------------------------------------------------------------------
# Harvest: spec -> all.cddl
# ---------------------------------------------------------------------------

PRE_RE = re.compile(
    r"<pre\b[^>]*\bclass\s*=\s*['\"][^'\"]*cddl[^'\"]*['\"][^>]*>(.*?)</pre>",
    re.IGNORECASE | re.DOTALL,
)


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "bidi-protocol-generator"})
    with urllib.request.urlopen(request, timeout=120) as response:
        return response.read().decode("utf-8", "replace")


def unhtml(text: str) -> str:
    # Bikeshed specs embed editor notes as HTML comments inside <pre class=cddl>.
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL)
    for entity, char in (("&lt;", "<"), ("&gt;", ">"), ("&quot;", '"'), ("&#39;", "'"), ("&amp;", "&")):
        text = text.replace(entity, char)
    return text


def dedent(block: str) -> str:
    lines = block.split("\n")
    widths = [len(line) - len(line.lstrip()) for line in lines if line.strip()]
    pad = min(widths) if widths else 0
    return "\n".join(line[pad:] for line in lines)


def extract_cddl(html: str) -> str:
    blocks = [dedent(unhtml(m.group(1))).strip("\n") for m in PRE_RE.finditer(html)]
    return "\n\n".join(block for block in blocks if block.strip()) + "\n"


# ---------------------------------------------------------------------------
# Lexer
# ---------------------------------------------------------------------------

TOKEN_RE = re.compile(
    r"""
      (?P<ws>\s+)
    | (?P<comment>;[^\n]*)
    | (?P<string>"(?:\\.|[^"\\])*")
    | (?P<range>\.\.\.|\.\.)
    | (?P<ctrl>\.[A-Za-z][A-Za-z0-9]*)
    | (?P<ext>//)
    | (?P<arrow>=>)
    | (?P<num>-?\d+(?:\.\d+)?)
    | (?P<name>[A-Za-z_][A-Za-z0-9_.\-]*)
    | (?P<punct>[{}()\[\],:/?*+=])
    """,
    re.VERBOSE,
)

# `X .default Y` / `X .ge Y` ... : drop the control operator and its operand.
CTRL_WITH_OPERAND = {"default", "ge", "gt", "le", "lt", "regexp", "eq", "ne",
                     "minLength", "maxLength", "size", "within", "and", "lt"}


def lex(text: str) -> list[tuple[str, str]]:
    tokens: list[tuple[str, str]] = []
    pos = 0
    while pos < len(text):
        match = TOKEN_RE.match(text, pos)
        if not match:
            raise ValueError(f"unexpected character at {pos}: {text[pos:pos+20]!r}")
        pos = match.end()
        kind = match.lastgroup
        if kind in ("ws", "comment"):
            continue
        tokens.append((kind, match.group()))
    return tokens


def strip_controls(tokens: list[tuple[str, str]]) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    i = 0
    while i < len(tokens):
        kind, value = tokens[i]
        if kind == "ctrl":
            name = value[1:]
            i += 1
            if name in CTRL_WITH_OPERAND and i < len(tokens):
                i += 1  # drop the operand
            continue
        out.append((kind, value))
        i += 1
    return out


def normalize_commas(text: str) -> str:
    """CDDL allows newline-separated members; insert the missing commas.

    A member is inserted before a line that starts a new entry (`? key`,
    `* value`, `key:`) when the previous non-blank line did not already end in a
    separator.
    """
    out: list[str] = []
    depth = 0
    member_start = re.compile(r'^(?:\?|\*|\+|[A-Za-z_][\w.]*\s*:|"[^"]*"\s*:)')
    for line in text.splitlines():
        stripped = line.strip()
        prev = next((l.strip() for l in reversed(out) if l.strip()), "")
        if (
            depth > 0
            and prev
            and not prev.endswith((",", "{", "(", "[", "/", "//", "=>", "=", ":"))
            and member_start.match(stripped)
        ):
            out[-1] = out[-1] + ","
        depth += line.count("{") + line.count("(") + line.count("[")
        depth -= line.count("}") + line.count(")") + line.count("]")
        out.append(line)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# Parser -> AST
# ---------------------------------------------------------------------------
# Node kinds: prim, ref, literal, number, range, map, group, array, union,
#             member.


class Parser:
    def __init__(self, tokens: list[tuple[str, str]]):
        self.tokens = strip_controls(tokens)
        self.pos = 0

    def peek(self) -> tuple[str, str] | None:
        return self.tokens[self.pos] if self.pos < len(self.tokens) else None

    def value(self, offset: int = 0) -> str | None:
        if self.pos + offset < len(self.tokens):
            return self.tokens[self.pos + offset][1]
        return None

    def kind(self, offset: int = 0) -> str | None:
        if self.pos + offset < len(self.tokens):
            return self.tokens[self.pos + offset][0]
        return None

    def take(self) -> tuple[str, str]:
        token = self.tokens[self.pos]
        self.pos += 1
        return token

    def expect(self, value: str) -> None:
        if self.value() != value:
            raise ValueError(f"expected {value!r}, got {self.value()!r}")
        self.pos += 1

    def parse(self) -> dict:
        node = self.parse_union()
        return node

    def parse_union(self) -> dict:
        members = [self.parse_primary()]
        while self.value() in ("/", "//"):
            self.pos += 1
            members.append(self.parse_primary())
        if len(members) == 1:
            return members[0]
        return {"kind": "union", "members": members}

    def parse_primary(self) -> dict:
        kind, value = self.take()
        if kind == "punct" and value == "{":
            return self.parse_container("}")
        if kind == "punct" and value == "(":
            return self.parse_container(")")
        if kind == "punct" and value == "[":
            return self.parse_container("]")
        if kind == "string":
            return {"kind": "literal", "value": value[1:-1]}
        if kind == "num":
            if self.value() in ("..", "..."):
                self.pos += 1
                hi = self.take()[1]
                return {"kind": "range", "lo": value, "hi": hi}
            return {"kind": "number", "value": value}
        if kind == "name":
            if value in ("true", "false", "null"):
                return {"kind": "literal", "value": value}
            if value in PRIMS:
                return {"kind": "prim", "name": value}
            return {"kind": "ref", "name": value}
        raise ValueError(f"unexpected token {(kind, value)!r}")

    def parse_container(self, close: str) -> dict:
        members = []
        while self.value() != close:
            members.append(self.parse_member())
            if self.value() == ",":
                self.pos += 1
        self.expect(close)
        kind = {"}": "map", ")": "group", "]": "array"}[close]
        return {"kind": kind, "members": members}

    def parse_member(self) -> dict:
        optional = False
        occurrence = None
        if self.value() == "?":
            optional = True
            self.pos += 1
        elif self.value() in ("*", "+"):
            occurrence = self.value()
            self.pos += 1

        # Map wildcard: `* text => any` (dropped).
        if occurrence and self.kind() == "name" and self.value(1) == "=>":
            self.pos += 3  # name, =>, value
            return {"kind": "member", "drop": True}

        # `* text` array element without a key.
        key = None
        if self.kind() in ("name", "string") and self.value(1) == ":":
            key = self.take()[1].strip('"')
            self.pos += 1  # ':'
        value = self.parse_union()
        return {
            "kind": "member",
            "key": key,
            "value": value,
            "optional": optional,
            "occurrence": occurrence,
        }


def refs_of(node: dict) -> list[dict]:
    """Reference nodes inside a value, flattening a `//` union."""
    if not isinstance(node, dict):
        return []
    if node.get("kind") == "ref":
        return [node]
    if node.get("kind") == "union":
        return [m for m in node["members"] if m.get("kind") == "ref"]
    return []


def collect_refs(node: dict) -> list[dict]:
    """Return the keyless reference members of a group/union dispatch definition."""
    if node.get("kind") in ("group", "map"):
        out: list[dict] = []
        for m in node.get("members", []):
            if m.get("drop") or m.get("key") is not None:
                continue
            out.extend(refs_of(m.get("value")))
        return out
    if node.get("kind") == "union":
        return refs_of(node)
    return []


def split_definitions(cddl: str) -> list[tuple[str, str]]:
    """Split `all.cddl` into ``(name, rhs)`` pairs (definitions start at col 0)."""
    defs: list[tuple[str, str]] = []
    name = None
    lines: list[str] = []
    for line in cddl.splitlines():
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_.]*)\s*=\s*(.*)$", line)
        if match:
            if name is not None:
                defs.append((name, "\n".join(lines)))
            name = match.group(1)
            lines = [match.group(2)]
        elif name is not None:
            lines.append(line)
    if name is not None:
        defs.append((name, "\n".join(lines)))
    return defs


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def to_snake(name: str) -> str:
    name = name.replace("-", "_")
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"_+", "_", name).lower()
    if name in {
        "type", "match", "move", "ref", "self", "super", "crate", "fn", "impl",
        "struct", "enum", "let", "mut", "loop", "const", "static", "dyn", "async",
        "await", "where", "for", "in", "as", "use", "mod", "trait", "pub", "box",
        "abstract", "become", "do", "final", "macro", "override", "priv", "try",
        "typeof", "unsized", "virtual", "yield", "union",
    }:
        name += "_"
    return name


def to_upper_camel(name: str) -> str:
    parts = re.split(r"[^A-Za-z0-9]+", name)
    out = "".join(p[:1].upper() + p[1:] for p in parts if p)
    if not out:
        out = "Value"
    if out[0].isdigit():
        out = "N" + out
    if out in ("Self", "Super", "Crate"):
        out += "Value"
    return out


def module_of(name: str) -> str:
    return name.split(".", 1)[0] if "." in name else ""


def module_ident(prefix: str) -> str:
    return MODULE_NAMES.get(prefix, prefix.lower())


def type_leaf(name: str) -> str:
    return name.split(".", 1)[1] if "." in name else name


# ---------------------------------------------------------------------------
# Type mapping
# ---------------------------------------------------------------------------

class Generator:
    def __init__(self, defs: dict[str, dict]):
        self.defs = defs
        self.commands = set()   # dotted names that are commands
        self.events = set()     # dotted names that are events

    # -- reference resolution ------------------------------------------------
    def map_ref(self, name: str) -> str | None:
        if name == "Extensible":
            return None
        if name in PRIMS:
            return PRIMS[name]
        if "." in name:
            module, leaf = name.split(".", 1)
            return f"crate::{module_ident(module)}::{leaf}"
        if name in self.defs or name in SKIP_ROOT or name in ("EmptyResult", "EmptyParams"):
            return f"crate::{name}"
        return None

    def rust_type(self, node: dict) -> str:
        kind = node["kind"]
        if kind == "prim":
            return PRIMS[node["name"]]
        if kind == "literal":
            return "String"
        if kind == "number":
            return "f64" if "." in node["value"] else "i64"
        if kind == "range":
            return "f64" if ("." in node["lo"] or "." in node["hi"]) else "u64"
        if kind == "ref":
            mapped = self.map_ref(node["name"])
            return mapped if mapped else "JsonValue"
        if kind == "array":
            inner = self.array_element(node)
            return f"Vec<{inner}>" if inner else "Vec<JsonValue>"
        # Inline maps, groups and unions collapse to a permissive JSON value.
        return "JsonValue"

    def array_element(self, node: dict) -> str | None:
        if len(node["members"]) != 1:
            return None
        member = node["members"][0]
        if member.get("drop"):
            return None
        return self.rust_type(member["value"])

    # -- definition emission -------------------------------------------------
    def field(self, member: dict) -> str | None:
        if member.get("drop") or member["key"] is None:
            return None
        value = member["value"]
        rust = self.rust_type(value)
        if member["optional"]:
            rust = f"Option<{rust}>"
        attrs = []
        if member["key"] != to_snake(member["key"]):
            attrs.append(f'rename = "{member["key"]}"')
        if member["optional"]:
            attrs.append('skip_serializing_if = "Option::is_none"')
        attr = f"    #[serde({', '.join(attrs)})]\n" if attrs else ""
        return f"{attr}    pub {to_snake(member['key'])}: {rust},"

    def emit_struct(self, name: str, node: dict) -> list[str]:
        lines = ["#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]",
                 '#[serde(rename_all = "camelCase")]',
                 f"pub struct {name} {{"]
        for member in node["members"]:
            if member.get("drop"):
                continue
            if member["key"] is None:
                # Group spread: `{ browsingContext.BaseInfo }` -> flatten.
                inner = self.rust_type(member["value"])
                if inner == "JsonValue":
                    continue
                field_name = to_snake(type_leaf(member["value"].get("name", "base")))
                lines.append("    #[serde(flatten)]")
                lines.append(f"    pub {field_name}: {inner},")
                continue
            rendered = self.field(member)
            if rendered:
                lines.append(rendered)
        lines.append("}")
        return lines

    def emit_string_enum(self, name: str, literals: list[str]) -> list[str]:
        lines = ["#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]",
                 f"pub enum {name} {{"]
        seen = set()
        for literal in literals:
            variant = to_upper_camel(literal)
            while variant in seen:
                variant += "Alt"
            seen.add(variant)
            lines.append(f'    #[serde(rename = "{literal}")]')
            lines.append(f"    {variant},")
        lines.append("}")
        return lines

    def emit_untagged_enum(self, name: str, refs: list[dict]) -> list[str]:
        lines = ["#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]",
                 "#[serde(untagged)]",
                 f"pub enum {name} {{"]
        seen = set()
        for ref in refs:
            rust = self.rust_type(ref)
            variant = to_upper_camel(type_leaf(ref.get("name", "value")))
            while variant in seen:
                variant += "Alt"
            seen.add(variant)
            lines.append(f"    {variant}({rust}),")
        lines.append("}")
        return lines

    def emit_alias(self, name: str, node: dict) -> list[str]:
        return [f"pub type {name} = {self.rust_type(node)};"]

    def classify(self, name: str, node: dict) -> list[str]:
        members = node.get("members")
        if node["kind"] == "map" and members is not None:
            real = [m for m in members if not m.get("drop")]
            if len(real) == 1 and real[0]["key"] is None:
                value = real[0]["value"]
                if value["kind"] == "union":
                    refs = refs_of(value)
                    if refs:
                        return self.emit_untagged_enum(name, refs)
                    return self.emit_alias(name, {"kind": "prim", "name": "any"})
                return self.emit_struct(name, node)
            return self.emit_struct(name, node)
        if node["kind"] == "group":
            keyed = [m for m in members if m.get("key") is not None]
            if keyed:
                return self.emit_struct(name, node)
            refs = collect_refs(node)
            if refs:
                return self.emit_untagged_enum(name, refs)
            return self.emit_alias(name, {"kind": "prim", "name": "any"})
        if node["kind"] == "union":
            if all(m["kind"] == "literal" for m in node["members"]):
                return self.emit_string_enum(name, [m["value"] for m in node["members"]])
            if all(m["kind"] == "ref" for m in node["members"]):
                return self.emit_untagged_enum(name, node["members"])
            return self.emit_alias(name, node)
        if node["kind"] == "literal":
            return self.emit_string_enum(name, [node["value"]])
        return self.emit_alias(name, node)

    # -- command / event discovery ------------------------------------------
    def discover(self) -> None:
        for name, node in self.defs.items():
            if name in SKIP_ROOT or node.get("kind") not in ("group", "union"):
                # Dispatch unions are parenthesised groups; the root `Command`
                # and `Event` are maps and must not be treated as one.
                continue
            if not name.endswith(("Command", "Event")):
                continue
            refs = [r["name"] for r in collect_refs(node)]
            if name.endswith("Command"):
                self.commands.update(refs)
            elif name.endswith("Event"):
                self.events.update(refs)

    def command_method(self, dotted: str) -> tuple[str, str, str]:
        node = self.defs.get(dotted)
        method = ""
        params = "crate::EmptyParams"
        if node:
            for member in node.get("members", []):
                if member.get("key") == "method":
                    method = member["value"].get("value", "")
                elif member.get("key") == "params":
                    mapped = self.rust_type(member["value"])
                    if mapped != "JsonValue":
                        params = mapped
        result_name = dotted + "Result"
        response = f"crate::{module_ident(module_of(result_name))}::{type_leaf(result_name)}"
        if result_name not in self.defs:
            response = "crate::EmptyResult"
        return method, params, response

    def event_method(self, dotted: str) -> tuple[str, str]:
        node = self.defs.get(dotted)
        method = ""
        params = "JsonValue"
        if node:
            for member in node.get("members", []):
                if member.get("key") == "method":
                    method = member["value"].get("value", "")
                elif member.get("key") == "params":
                    mapped = self.rust_type(member["value"])
                    params = mapped if mapped != "JsonValue" else "JsonValue"
        return method, params

    def emit_command(self, dotted: str) -> list[str]:
        method, params, response = self.command_method(dotted)
        name = type_leaf(dotted)
        return [
            f"/// `{method}`",
            f"pub struct {name};",
            f"impl crate::BidiCommand for {name} {{",
            f'    const METHOD: &\'static str = "{method}";',
            f"    type Params = {params};",
            f"    type Response = {response};",
            "}",
        ]

    def emit_event(self, dotted: str) -> list[str]:
        method, params = self.event_method(dotted)
        name = type_leaf(dotted)
        return [
            f"/// `{method}`",
            f"pub struct {name};",
            f"impl crate::BidiEvent for {name} {{",
            f'    const METHOD: &\'static str = "{method}";',
            f"    type Params = {params};",
            "}",
        ]


# ---------------------------------------------------------------------------
# Generate
# ---------------------------------------------------------------------------

def is_dispatch_union(name: str, node: dict) -> bool:
    """A module-level `<Module>Command` / `<Module>Result` / `<Module>Event` union.

    These have no dotted prefix (e.g. `BrowsingContextResult`); dotted unions such
    as `script.EvaluateResult` are real types and must be generated.
    """
    if "." in name:
        return False
    if not name.endswith(("Command", "Result", "Event")):
        return False
    if node["kind"] not in ("group", "union", "map"):
        return False
    return bool(collect_refs(node))


def generate(cddl: str) -> None:
    definitions = split_definitions(normalize_commas(cddl))
    defs: dict[str, dict] = {}
    for name, rhs in definitions:
        try:
            defs[name] = Parser(lex(rhs)).parse()
        except Exception as error:  # noqa: BLE001 - tolerate spec irregularities
            print(f"  ! skipped {name}: {error}")

    gen = Generator(defs)
    gen.discover()

    modules: dict[str, list[str]] = {}
    root: list[str] = []

    for name in sorted(defs):
        if name in SKIP_ROOT:
            continue
        if name in gen.commands or name in gen.events:
            # Command/event groups become marker structs below.
            continue
        node = defs[name]
        if is_dispatch_union(name, node):
            continue
        try:
            emitted = gen.classify(type_leaf(name), node)
        except Exception as error:  # noqa: BLE001
            print(f"  ! failed {name}: {error}")
            continue
        target = root if module_of(name) == "" else modules.setdefault(module_ident(module_of(name)), [])
        target.append(f"/// `{name}`")
        target.extend(emitted)
        target.append("")

    # Command / event marker impls, grouped by module.
    for dotted in sorted(gen.commands):
        if dotted not in defs:
            continue
        module = module_ident(module_of(dotted)) or "root"
        bucket = root if module == "root" else modules.setdefault(module, [])
        bucket.extend(gen.emit_command(dotted))
        bucket.append("")

    for dotted in sorted(gen.events):
        if dotted not in defs:
            continue
        module = module_ident(module_of(dotted)) or "root"
        bucket = root if module == "root" else modules.setdefault(module, [])
        bucket.extend(gen.emit_event(dotted))
        bucket.append("")

    os.makedirs(SRC, exist_ok=True)
    for module in sorted(modules):
        write_module(module, modules[module])

    write_lib(sorted(modules), root)
    print(f"generated {len(defs)} definitions into {len(modules)} modules + root")


def write_module(module: str, body: list[str]) -> None:
    directory = os.path.join(SRC, module)
    os.makedirs(directory, exist_ok=True)
    header = [
        "// @generated by scripts/generate_rust_code.py -- do not edit by hand.",
        "#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]",
        "",
        "use serde::{Deserialize, Serialize};",
        "use serde_json::Value as JsonValue;",
        "use crate::{BidiCommand, BidiEvent};",
        "",
    ]
    with open(os.path.join(directory, "mod.rs"), "w", encoding="utf-8") as handle:
        handle.write("\n".join(header + body) + "\n")


def write_lib(modules: list[str], root: list[str]) -> None:
    declarations = [f"pub mod {module};" for module in modules]
    content = "\n".join([PROLOGUE, "", "\n".join(declarations), "", "\n".join(root)]) + "\n"
    with open(os.path.join(SRC, "lib.rs"), "w", encoding="utf-8") as handle:
        handle.write(content)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", help="path to a local index.bs (defaults to downloading)")
    parser.add_argument("--cddl", help="regenerate from a local all.cddl (skips extraction)")
    parser.add_argument("--check", action="store_true", help="exit 1 if the remote spec differs")
    args = parser.parse_args()

    if args.check:
        current = open(SPEC_FILE, encoding="utf-8").read() if os.path.exists(SPEC_FILE) else ""
        sys.exit(0 if current == fetch(SPEC_URL) else 1)

    if args.cddl:
        cddl = open(args.cddl, encoding="utf-8").read()
        print(f"regenerating from {args.cddl}")
        generate(cddl)
        return

    if args.spec:
        html = open(args.spec, encoding="utf-8").read()
        spec_path = args.spec
    else:
        html = fetch(SPEC_URL)
        with open(SPEC_FILE, "w", encoding="utf-8") as handle:
            handle.write(html)
        spec_path = SPEC_FILE

    cddl = extract_cddl(html)
    with open(CDDL_FILE, "w", encoding="utf-8") as handle:
        handle.write(cddl)
    print(f"harvested CDDL from {spec_path} -> {CDDL_FILE}")
    generate(cddl)


if __name__ == "__main__":
    main()
