// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `input.ElementOrigin`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ElementOrigin {
    #[serde(rename = "type")]
    pub type_: String,
    pub element: crate::script::SharedReference,
}

/// `input.FileDialogInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FileDialogInfo {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub element: Option<crate::script::SharedReference>,
    pub multiple: bool,
}

/// `input.KeyDownAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct KeyDownAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `input.KeySourceAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum KeySourceAction {
    PauseAction(crate::input::PauseAction),
    KeyDownAction(crate::input::KeyDownAction),
    KeyUpAction(crate::input::KeyUpAction),
}

/// `input.KeySourceActions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct KeySourceActions {
    #[serde(rename = "type")]
    pub type_: String,
    pub id: String,
    pub actions: Vec<crate::input::KeySourceAction>,
}

/// `input.KeyUpAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct KeyUpAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `input.NoneSourceAction`
pub type NoneSourceAction = crate::input::PauseAction;

/// `input.NoneSourceActions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NoneSourceActions {
    #[serde(rename = "type")]
    pub type_: String,
    pub id: String,
    pub actions: Vec<crate::input::NoneSourceAction>,
}

/// `input.Origin`
pub type Origin = JsonValue;

/// `input.PauseAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PauseAction {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<u64>,
}

/// `input.PerformActionsParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PerformActionsParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub actions: Vec<crate::input::SourceActions>,
}

/// `input.PerformActionsResult`
pub type PerformActionsResult = crate::EmptyResult;

/// `input.PointerCommonProperties`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerCommonProperties {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pressure: Option<JsonValue>,
    #[serde(rename = "tangentialPressure", skip_serializing_if = "Option::is_none")]
    pub tangential_pressure: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub twist: Option<JsonValue>,
    #[serde(rename = "altitudeAngle", skip_serializing_if = "Option::is_none")]
    pub altitude_angle: Option<JsonValue>,
    #[serde(rename = "azimuthAngle", skip_serializing_if = "Option::is_none")]
    pub azimuth_angle: Option<JsonValue>,
}

/// `input.PointerDownAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerDownAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub button: u64,
    #[serde(flatten)]
    pub pointer_common_properties: crate::input::PointerCommonProperties,
}

/// `input.PointerMoveAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerMoveAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub x: f64,
    pub y: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin: Option<crate::input::Origin>,
    #[serde(flatten)]
    pub pointer_common_properties: crate::input::PointerCommonProperties,
}

/// `input.PointerParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerParameters {
    #[serde(rename = "pointerType", skip_serializing_if = "Option::is_none")]
    pub pointer_type: Option<crate::input::PointerType>,
}

/// `input.PointerSourceAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum PointerSourceAction {
    PauseAction(crate::input::PauseAction),
    PointerDownAction(crate::input::PointerDownAction),
    PointerUpAction(crate::input::PointerUpAction),
    PointerMoveAction(crate::input::PointerMoveAction),
}

/// `input.PointerSourceActions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerSourceActions {
    #[serde(rename = "type")]
    pub type_: String,
    pub id: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parameters: Option<crate::input::PointerParameters>,
    pub actions: Vec<crate::input::PointerSourceAction>,
}

/// `input.PointerType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PointerType {
    #[serde(rename = "mouse")]
    Mouse,
    #[serde(rename = "pen")]
    Pen,
    #[serde(rename = "touch")]
    Touch,
}

/// `input.PointerUpAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PointerUpAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub button: u64,
}

/// `input.ReleaseActionsParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ReleaseActionsParameters {
    pub context: crate::browsing_context::BrowsingContext,
}

/// `input.ReleaseActionsResult`
pub type ReleaseActionsResult = crate::EmptyResult;

/// `input.SetFilesParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetFilesParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub element: crate::script::SharedReference,
    pub files: Vec<String>,
}

/// `input.SetFilesResult`
pub type SetFilesResult = crate::EmptyResult;

/// `input.SourceActions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum SourceActions {
    NoneSourceActions(crate::input::NoneSourceActions),
    KeySourceActions(crate::input::KeySourceActions),
    PointerSourceActions(crate::input::PointerSourceActions),
    WheelSourceActions(crate::input::WheelSourceActions),
}

/// `input.WheelScrollAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WheelScrollAction {
    #[serde(rename = "type")]
    pub type_: String,
    pub x: i64,
    pub y: i64,
    #[serde(rename = "deltaX")]
    pub delta_x: i64,
    #[serde(rename = "deltaY")]
    pub delta_y: i64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin: Option<crate::input::Origin>,
}

/// `input.WheelSourceAction`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum WheelSourceAction {
    PauseAction(crate::input::PauseAction),
    WheelScrollAction(crate::input::WheelScrollAction),
}

/// `input.WheelSourceActions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WheelSourceActions {
    #[serde(rename = "type")]
    pub type_: String,
    pub id: String,
    pub actions: Vec<crate::input::WheelSourceAction>,
}

/// `input.performActions`
pub struct PerformActions;
impl crate::BidiCommand for PerformActions {
    const METHOD: &'static str = "input.performActions";
    type Params = crate::input::PerformActionsParameters;
    type Response = crate::input::PerformActionsResult;
}

/// `input.releaseActions`
pub struct ReleaseActions;
impl crate::BidiCommand for ReleaseActions {
    const METHOD: &'static str = "input.releaseActions";
    type Params = crate::input::ReleaseActionsParameters;
    type Response = crate::input::ReleaseActionsResult;
}

/// `input.setFiles`
pub struct SetFiles;
impl crate::BidiCommand for SetFiles {
    const METHOD: &'static str = "input.setFiles";
    type Params = crate::input::SetFilesParameters;
    type Response = crate::input::SetFilesResult;
}

/// `input.fileDialogOpened`
pub struct FileDialogOpened;
impl crate::BidiEvent for FileDialogOpened {
    const METHOD: &'static str = "input.fileDialogOpened";
    type Params = crate::input::FileDialogInfo;
}

