// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `browser.ClientWindow`
pub type ClientWindow = String;

/// `browser.ClientWindowInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ClientWindowInfo {
    pub active: bool,
    #[serde(rename = "clientWindow")]
    pub client_window: crate::browser::ClientWindow,
    pub height: u64,
    pub state: JsonValue,
    pub width: u64,
    pub x: i64,
    pub y: i64,
}

/// `browser.ClientWindowNamedState`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ClientWindowNamedState {
    pub state: JsonValue,
}

/// `browser.ClientWindowRectState`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ClientWindowRectState {
    pub state: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub x: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub y: Option<i64>,
}

/// `browser.CloseResult`
pub type CloseResult = crate::EmptyResult;

/// `browser.CreateUserContextParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CreateUserContextParameters {
    #[serde(rename = "acceptInsecureCerts", skip_serializing_if = "Option::is_none")]
    pub accept_insecure_certs: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub proxy: Option<crate::session::ProxyConfiguration>,
    #[serde(rename = "unhandledPromptBehavior", skip_serializing_if = "Option::is_none")]
    pub unhandled_prompt_behavior: Option<crate::session::UserPromptHandler>,
}

/// `browser.CreateUserContextResult`
pub type CreateUserContextResult = crate::browser::UserContextInfo;

/// `browser.DownloadBehavior`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadBehavior {
}

/// `browser.DownloadBehaviorAllowed`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadBehaviorAllowed {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "destinationFolder")]
    pub destination_folder: String,
}

/// `browser.DownloadBehaviorDenied`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadBehaviorDenied {
    #[serde(rename = "type")]
    pub type_: String,
}

/// `browser.GetClientWindowsResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetClientWindowsResult {
    #[serde(rename = "clientWindows")]
    pub client_windows: Vec<crate::browser::ClientWindowInfo>,
}

/// `browser.GetUserContextsResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetUserContextsResult {
    #[serde(rename = "userContexts")]
    pub user_contexts: Vec<crate::browser::UserContextInfo>,
}

/// `browser.RemoveUserContextParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RemoveUserContextParameters {
    #[serde(rename = "userContext")]
    pub user_context: crate::browser::UserContext,
}

/// `browser.RemoveUserContextResult`
pub type RemoveUserContextResult = crate::EmptyResult;

/// `browser.SetClientWindowStateParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetClientWindowStateParameters {
    #[serde(rename = "clientWindow")]
    pub client_window: crate::browser::ClientWindow,
}

/// `browser.SetClientWindowStateResult`
pub type SetClientWindowStateResult = crate::browser::ClientWindowInfo;

/// `browser.SetDownloadBehaviorParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetDownloadBehaviorParameters {
    #[serde(rename = "downloadBehavior")]
    pub download_behavior: JsonValue,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `browser.SetDownloadBehaviorResult`
pub type SetDownloadBehaviorResult = crate::EmptyResult;

/// `browser.UserContext`
pub type UserContext = String;

/// `browser.UserContextInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UserContextInfo {
    #[serde(rename = "userContext")]
    pub user_context: crate::browser::UserContext,
}

/// `browser.close`
pub struct Close;
impl crate::BidiCommand for Close {
    const METHOD: &'static str = "browser.close";
    type Params = crate::EmptyParams;
    type Response = crate::browser::CloseResult;
}

/// `browser.createUserContext`
pub struct CreateUserContext;
impl crate::BidiCommand for CreateUserContext {
    const METHOD: &'static str = "browser.createUserContext";
    type Params = crate::browser::CreateUserContextParameters;
    type Response = crate::browser::CreateUserContextResult;
}

/// `browser.getClientWindows`
pub struct GetClientWindows;
impl crate::BidiCommand for GetClientWindows {
    const METHOD: &'static str = "browser.getClientWindows";
    type Params = crate::EmptyParams;
    type Response = crate::browser::GetClientWindowsResult;
}

/// `browser.getUserContexts`
pub struct GetUserContexts;
impl crate::BidiCommand for GetUserContexts {
    const METHOD: &'static str = "browser.getUserContexts";
    type Params = crate::EmptyParams;
    type Response = crate::browser::GetUserContextsResult;
}

/// `browser.removeUserContext`
pub struct RemoveUserContext;
impl crate::BidiCommand for RemoveUserContext {
    const METHOD: &'static str = "browser.removeUserContext";
    type Params = crate::browser::RemoveUserContextParameters;
    type Response = crate::browser::RemoveUserContextResult;
}

/// `browser.setClientWindowState`
pub struct SetClientWindowState;
impl crate::BidiCommand for SetClientWindowState {
    const METHOD: &'static str = "browser.setClientWindowState";
    type Params = crate::browser::SetClientWindowStateParameters;
    type Response = crate::browser::SetClientWindowStateResult;
}

/// `browser.setDownloadBehavior`
pub struct SetDownloadBehavior;
impl crate::BidiCommand for SetDownloadBehavior {
    const METHOD: &'static str = "browser.setDownloadBehavior";
    type Params = crate::browser::SetDownloadBehaviorParameters;
    type Response = crate::browser::SetDownloadBehaviorResult;
}

