// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Xcelerate
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "xcelerate";





        [DllImport(__DllName, EntryPoint = "xcel_free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void xcel_free_string(byte* ptr);

        [DllImport(__DllName, EntryPoint = "xcel_free_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void xcel_free_buffer(ByteBuffer buf);

        [DllImport(__DllName, EntryPoint = "xcel_browser_launch", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* xcel_browser_launch([MarshalAs(UnmanagedType.U1)] bool headless);

        [DllImport(__DllName, EntryPoint = "xcel_browser_new_page", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* xcel_browser_new_page(void* browser_ptr, byte* url);

        [DllImport(__DllName, EntryPoint = "xcel_browser_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_browser_version(void* browser_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_browser_targets", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_browser_targets(void* browser_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_navigate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_page_navigate(void* page_ptr, byte* url);

        [DllImport(__DllName, EntryPoint = "xcel_page_title", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_page_title(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_content", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_page_content(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_screenshot", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer xcel_page_screenshot(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_pdf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer xcel_page_pdf(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_wait_for_selector", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* xcel_page_wait_for_selector(void* page_ptr, byte* selector);

        [DllImport(__DllName, EntryPoint = "xcel_page_wait_for_navigation", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_page_wait_for_navigation(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_evaluate", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_page_evaluate(void* page_ptr, byte* expression);

        [DllImport(__DllName, EntryPoint = "xcel_page_reload", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_page_reload(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_go_back", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_page_go_back(void* page_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_page_add_script_to_evaluate_on_new_document", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_page_add_script_to_evaluate_on_new_document(void* page_ptr, byte* source);

        [DllImport(__DllName, EntryPoint = "xcel_element_click", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_element_click(void* el_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_element_type_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_element_type_text(void* el_ptr, byte* text);

        [DllImport(__DllName, EntryPoint = "xcel_element_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_element_text(void* el_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_element_hover", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_element_hover(void* el_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_element_focus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool xcel_element_focus(void* el_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_element_inner_html", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_element_inner_html(void* el_ptr);

        [DllImport(__DllName, EntryPoint = "xcel_element_attribute", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* xcel_element_attribute(void* el_ptr, byte* name);

        [DllImport(__DllName, EntryPoint = "xcel_free_browser", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void xcel_free_browser(void* ptr);

        [DllImport(__DllName, EntryPoint = "xcel_free_page", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void xcel_free_page(void* ptr);

        [DllImport(__DllName, EntryPoint = "xcel_free_element", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void xcel_free_element(void* ptr);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public nuint len;
    }



}
