# Generated by scripts/generate_bindings/ruby.py - edit the script, not this.
Gem::Specification.new do |spec|
  spec.name          = "xcelerate"
  spec.version       = "1.0.9"
  spec.summary       = "Chrome DevTools Protocol client for Ruby (xcelerate core)."
  spec.description   = "Ruby bindings for the xcelerate CDP engine, generated with UniFFI."
  spec.authors       = ["AzzoDude"]
  spec.homepage      = "https://github.com/AzzoDude/xcelerate"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.1"

  spec.files = Dir["lib/**/*.rb", "*.dll", "*.so", "*.dylib"]
  spec.require_paths = ["lib"]
  spec.add_dependency "ffi", "~> 1.15"
end
