// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `webExtension.Extension`
pub type Extension = String;

/// `webExtension.ExtensionArchivePath`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExtensionArchivePath {
    #[serde(rename = "type")]
    pub type_: String,
    pub path: String,
}

/// `webExtension.ExtensionBase64Encoded`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExtensionBase64Encoded {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `webExtension.ExtensionData`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ExtensionData {
    ExtensionArchivePath(crate::web_extension::ExtensionArchivePath),
    ExtensionBase64Encoded(crate::web_extension::ExtensionBase64Encoded),
    ExtensionPath(crate::web_extension::ExtensionPath),
}

/// `webExtension.ExtensionPath`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExtensionPath {
    #[serde(rename = "type")]
    pub type_: String,
    pub path: String,
}

/// `webExtension.InstallParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstallParameters {
    #[serde(rename = "extensionData")]
    pub extension_data: crate::web_extension::ExtensionData,
}

/// `webExtension.InstallResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InstallResult {
    pub extension: crate::web_extension::Extension,
}

/// `webExtension.UninstallParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UninstallParameters {
    pub extension: crate::web_extension::Extension,
}

/// `webExtension.UninstallResult`
pub type UninstallResult = crate::EmptyResult;

/// `webExtension.install`
pub struct Install;
impl crate::BidiCommand for Install {
    const METHOD: &'static str = "webExtension.install";
    type Params = crate::web_extension::InstallParameters;
    type Response = crate::web_extension::InstallResult;
}

/// `webExtension.uninstall`
pub struct Uninstall;
impl crate::BidiCommand for Uninstall {
    const METHOD: &'static str = "webExtension.uninstall";
    type Params = crate::web_extension::UninstallParameters;
    type Response = crate::web_extension::UninstallResult;
}

