// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `browsingContext.AccessibilityLocator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AccessibilityLocator {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: JsonValue,
}

/// `browsingContext.ActivateParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ActivateParameters {
    pub context: crate::browsing_context::BrowsingContext,
}

/// `browsingContext.ActivateResult`
pub type ActivateResult = crate::EmptyResult;

/// `browsingContext.BaseInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BaseInfo {
    pub children: JsonValue,
    #[serde(rename = "clientWindow")]
    pub client_window: crate::browser::ClientWindow,
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "originalOpener")]
    pub original_opener: JsonValue,
    pub url: String,
    #[serde(rename = "userContext")]
    pub user_context: crate::browser::UserContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub parent: Option<JsonValue>,
}

/// `browsingContext.BaseNavigationInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BaseNavigationInfo {
    pub context: crate::browsing_context::BrowsingContext,
    pub navigation: JsonValue,
    pub timestamp: u64,
    pub url: String,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
}

/// `browsingContext.BoxClipRectangle`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BoxClipRectangle {
    #[serde(rename = "type")]
    pub type_: String,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
}

/// `browsingContext.BrowsingContext`
pub type BrowsingContext = String;

/// `browsingContext.CaptureScreenshotParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CaptureScreenshotParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub origin: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<crate::browsing_context::ImageFormat>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub clip: Option<crate::browsing_context::ClipRectangle>,
    #[serde(rename = "imageSize", skip_serializing_if = "Option::is_none")]
    pub image_size: Option<crate::browsing_context::ImageSize>,
}

/// `browsingContext.CaptureScreenshotResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CaptureScreenshotResult {
    pub data: String,
}

/// `browsingContext.ClipRectangle`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum ClipRectangle {
    BoxClipRectangle(crate::browsing_context::BoxClipRectangle),
    ElementClipRectangle(crate::browsing_context::ElementClipRectangle),
}

/// `browsingContext.CloseParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CloseParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "promptUnload", skip_serializing_if = "Option::is_none")]
    pub prompt_unload: Option<bool>,
}

/// `browsingContext.CloseResult`
pub type CloseResult = crate::EmptyResult;

/// `browsingContext.ContextCreatedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContextCreatedParameters {
    #[serde(flatten)]
    pub base_info: crate::browsing_context::BaseInfo,
    #[serde(rename = "hasPlannedNavigation")]
    pub has_planned_navigation: bool,
}

/// `browsingContext.ContextLocator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContextLocator {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: JsonValue,
}

/// `browsingContext.CreateParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CreateParameters {
    #[serde(rename = "type")]
    pub type_: crate::browsing_context::CreateType,
    #[serde(rename = "referenceContext", skip_serializing_if = "Option::is_none")]
    pub reference_context: Option<crate::browsing_context::BrowsingContext>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background: Option<bool>,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
}

/// `browsingContext.CreateResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CreateResult {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
}

/// `browsingContext.CreateType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum CreateType {
    #[serde(rename = "tab")]
    Tab,
    #[serde(rename = "window")]
    Window,
}

/// `browsingContext.CssLocator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CssLocator {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `browsingContext.Download`
pub type Download = String;

/// `browsingContext.DownloadCanceledParams`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadCanceledParams {
    pub status: String,
    pub download: crate::browsing_context::Download,
    #[serde(flatten)]
    pub base_navigation_info: crate::browsing_context::BaseNavigationInfo,
}

/// `browsingContext.DownloadCompleteParams`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadCompleteParams {
    pub status: String,
    pub download: crate::browsing_context::Download,
    pub filepath: JsonValue,
    #[serde(flatten)]
    pub base_navigation_info: crate::browsing_context::BaseNavigationInfo,
}

/// `browsingContext.DownloadEndParams`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadEndParams {
}

/// `browsingContext.DownloadWillBeginParams`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DownloadWillBeginParams {
    pub download: crate::browsing_context::Download,
    #[serde(rename = "suggestedFilename")]
    pub suggested_filename: String,
    #[serde(flatten)]
    pub base_navigation_info: crate::browsing_context::BaseNavigationInfo,
}

/// `browsingContext.ElementClipRectangle`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ElementClipRectangle {
    #[serde(rename = "type")]
    pub type_: String,
    pub element: crate::script::SharedReference,
}

/// `browsingContext.GetTreeParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetTreeParameters {
    #[serde(rename = "maxDepth", skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub root: Option<crate::browsing_context::BrowsingContext>,
}

/// `browsingContext.GetTreeResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetTreeResult {
    pub contexts: crate::browsing_context::InfoList,
}

/// `browsingContext.HandleUserPromptParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HandleUserPromptParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accept: Option<bool>,
    #[serde(rename = "userText", skip_serializing_if = "Option::is_none")]
    pub user_text: Option<String>,
}

/// `browsingContext.HandleUserPromptResult`
pub type HandleUserPromptResult = crate::EmptyResult;

/// `browsingContext.HistoryUpdatedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HistoryUpdatedParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub timestamp: u64,
    pub url: String,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
}

/// `browsingContext.ImageFormat`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ImageFormat {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quality: Option<f64>,
}

/// `browsingContext.ImageSize`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ImageSize {
    #[serde(rename = "maxWidth", skip_serializing_if = "Option::is_none")]
    pub max_width: Option<JsonValue>,
    #[serde(rename = "maxHeight", skip_serializing_if = "Option::is_none")]
    pub max_height: Option<JsonValue>,
}

/// `browsingContext.Info`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Info {
    #[serde(flatten)]
    pub base_info: crate::browsing_context::BaseInfo,
}

/// `browsingContext.InfoList`
pub type InfoList = Vec<crate::browsing_context::Info>;

/// `browsingContext.InnerTextLocator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct InnerTextLocator {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
    #[serde(rename = "ignoreCase", skip_serializing_if = "Option::is_none")]
    pub ignore_case: Option<bool>,
    #[serde(rename = "matchType", skip_serializing_if = "Option::is_none")]
    pub match_type: Option<JsonValue>,
    #[serde(rename = "maxDepth", skip_serializing_if = "Option::is_none")]
    pub max_depth: Option<u64>,
}

/// `browsingContext.LocateNodesParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LocateNodesParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub locator: crate::browsing_context::Locator,
    #[serde(rename = "maxNodeCount", skip_serializing_if = "Option::is_none")]
    pub max_node_count: Option<JsonValue>,
    #[serde(rename = "serializationOptions", skip_serializing_if = "Option::is_none")]
    pub serialization_options: Option<crate::script::SerializationOptions>,
    #[serde(rename = "startNodes", skip_serializing_if = "Option::is_none")]
    pub start_nodes: Option<Vec<crate::script::SharedReference>>,
}

/// `browsingContext.LocateNodesResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct LocateNodesResult {
    pub nodes: Vec<crate::script::NodeRemoteValue>,
}

/// `browsingContext.Locator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum Locator {
    AccessibilityLocator(crate::browsing_context::AccessibilityLocator),
    CssLocator(crate::browsing_context::CssLocator),
    ContextLocator(crate::browsing_context::ContextLocator),
    InnerTextLocator(crate::browsing_context::InnerTextLocator),
    XPathLocator(crate::browsing_context::XPathLocator),
}

/// `browsingContext.MediaTrackConstraints`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MediaTrackConstraints {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<u64>,
    #[serde(rename = "frameRate", skip_serializing_if = "Option::is_none")]
    pub frame_rate: Option<u64>,
}

/// `browsingContext.NavigateParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NavigateParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wait: Option<crate::browsing_context::ReadinessState>,
}

/// `browsingContext.NavigateResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NavigateResult {
    pub navigation: JsonValue,
    pub url: String,
}

/// `browsingContext.Navigation`
pub type Navigation = String;

/// `browsingContext.NavigationInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NavigationInfo {
    #[serde(flatten)]
    pub base_navigation_info: crate::browsing_context::BaseNavigationInfo,
}

/// `browsingContext.PrintMarginParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PrintMarginParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bottom: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub left: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub right: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top: Option<JsonValue>,
}

/// `browsingContext.PrintPageParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PrintPageParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub height: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub width: Option<JsonValue>,
}

/// `browsingContext.PrintParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PrintParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub background: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub margin: Option<crate::browsing_context::PrintMarginParameters>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub orientation: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub page: Option<crate::browsing_context::PrintPageParameters>,
    #[serde(rename = "pageRanges", skip_serializing_if = "Option::is_none")]
    pub page_ranges: Option<Vec<JsonValue>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scale: Option<JsonValue>,
    #[serde(rename = "shrinkToFit", skip_serializing_if = "Option::is_none")]
    pub shrink_to_fit: Option<bool>,
}

/// `browsingContext.PrintResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PrintResult {
    pub data: String,
}

/// `browsingContext.ReadinessState`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ReadinessState {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "interactive")]
    Interactive,
    #[serde(rename = "complete")]
    Complete,
}

/// `browsingContext.ReloadParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ReloadParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "ignoreCache", skip_serializing_if = "Option::is_none")]
    pub ignore_cache: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub wait: Option<crate::browsing_context::ReadinessState>,
}

/// `browsingContext.ReloadResult`
pub type ReloadResult = crate::browsing_context::NavigateResult;

/// `browsingContext.Screencast`
pub type Screencast = String;

/// `browsingContext.SetBypassCSPParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetBypassCSPParameters {
    pub bypass: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `browsingContext.SetBypassCSPResult`
pub type SetBypassCSPResult = crate::EmptyResult;

/// `browsingContext.SetViewportParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetViewportParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<crate::browsing_context::BrowsingContext>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub viewport: Option<JsonValue>,
    #[serde(rename = "devicePixelRatio", skip_serializing_if = "Option::is_none")]
    pub device_pixel_ratio: Option<JsonValue>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `browsingContext.SetViewportResult`
pub type SetViewportResult = crate::EmptyResult;

/// `browsingContext.StartScreencastParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StartScreencastParameters {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "destinationFolder", skip_serializing_if = "Option::is_none")]
    pub destination_folder: Option<String>,
    #[serde(rename = "mimeType", skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub video: Option<crate::browsing_context::MediaTrackConstraints>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub audio: Option<bool>,
}

/// `browsingContext.StartScreencastResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StartScreencastResult {
    pub screencast: crate::browsing_context::Screencast,
    pub path: String,
}

/// `browsingContext.StopScreencastParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StopScreencastParameters {
    pub screencast: crate::browsing_context::Screencast,
}

/// `browsingContext.StopScreencastResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StopScreencastResult {
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// `browsingContext.TraverseHistoryParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct TraverseHistoryParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub delta: i64,
}

/// `browsingContext.TraverseHistoryResult`
pub type TraverseHistoryResult = crate::EmptyResult;

/// `browsingContext.UserPromptClosedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UserPromptClosedParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub accepted: bool,
    #[serde(rename = "type")]
    pub type_: crate::browsing_context::UserPromptType,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
    #[serde(rename = "userText", skip_serializing_if = "Option::is_none")]
    pub user_text: Option<String>,
}

/// `browsingContext.UserPromptOpenedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UserPromptOpenedParameters {
    pub context: crate::browsing_context::BrowsingContext,
    pub handler: crate::session::UserPromptHandlerType,
    pub message: String,
    #[serde(rename = "type")]
    pub type_: crate::browsing_context::UserPromptType,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
}

/// `browsingContext.UserPromptType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum UserPromptType {
    #[serde(rename = "alert")]
    Alert,
    #[serde(rename = "beforeunload")]
    Beforeunload,
    #[serde(rename = "confirm")]
    Confirm,
    #[serde(rename = "prompt")]
    Prompt,
}

/// `browsingContext.Viewport`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Viewport {
    pub width: u64,
    pub height: u64,
}

/// `browsingContext.XPathLocator`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct XPathLocator {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `browsingContext.activate`
pub struct Activate;
impl crate::BidiCommand for Activate {
    const METHOD: &'static str = "browsingContext.activate";
    type Params = crate::browsing_context::ActivateParameters;
    type Response = crate::browsing_context::ActivateResult;
}

/// `browsingContext.captureScreenshot`
pub struct CaptureScreenshot;
impl crate::BidiCommand for CaptureScreenshot {
    const METHOD: &'static str = "browsingContext.captureScreenshot";
    type Params = crate::browsing_context::CaptureScreenshotParameters;
    type Response = crate::browsing_context::CaptureScreenshotResult;
}

/// `browsingContext.close`
pub struct Close;
impl crate::BidiCommand for Close {
    const METHOD: &'static str = "browsingContext.close";
    type Params = crate::browsing_context::CloseParameters;
    type Response = crate::browsing_context::CloseResult;
}

/// `browsingContext.create`
pub struct Create;
impl crate::BidiCommand for Create {
    const METHOD: &'static str = "browsingContext.create";
    type Params = crate::browsing_context::CreateParameters;
    type Response = crate::browsing_context::CreateResult;
}

/// `browsingContext.getTree`
pub struct GetTree;
impl crate::BidiCommand for GetTree {
    const METHOD: &'static str = "browsingContext.getTree";
    type Params = crate::browsing_context::GetTreeParameters;
    type Response = crate::browsing_context::GetTreeResult;
}

/// `browsingContext.handleUserPrompt`
pub struct HandleUserPrompt;
impl crate::BidiCommand for HandleUserPrompt {
    const METHOD: &'static str = "browsingContext.handleUserPrompt";
    type Params = crate::browsing_context::HandleUserPromptParameters;
    type Response = crate::browsing_context::HandleUserPromptResult;
}

/// `browsingContext.locateNodes`
pub struct LocateNodes;
impl crate::BidiCommand for LocateNodes {
    const METHOD: &'static str = "browsingContext.locateNodes";
    type Params = crate::browsing_context::LocateNodesParameters;
    type Response = crate::browsing_context::LocateNodesResult;
}

/// `browsingContext.navigate`
pub struct Navigate;
impl crate::BidiCommand for Navigate {
    const METHOD: &'static str = "browsingContext.navigate";
    type Params = crate::browsing_context::NavigateParameters;
    type Response = crate::browsing_context::NavigateResult;
}

/// `browsingContext.print`
pub struct Print;
impl crate::BidiCommand for Print {
    const METHOD: &'static str = "browsingContext.print";
    type Params = crate::browsing_context::PrintParameters;
    type Response = crate::browsing_context::PrintResult;
}

/// `browsingContext.reload`
pub struct Reload;
impl crate::BidiCommand for Reload {
    const METHOD: &'static str = "browsingContext.reload";
    type Params = crate::browsing_context::ReloadParameters;
    type Response = crate::browsing_context::ReloadResult;
}

/// `browsingContext.setBypassCSP`
pub struct SetBypassCSP;
impl crate::BidiCommand for SetBypassCSP {
    const METHOD: &'static str = "browsingContext.setBypassCSP";
    type Params = crate::browsing_context::SetBypassCSPParameters;
    type Response = crate::browsing_context::SetBypassCSPResult;
}

/// `browsingContext.setViewport`
pub struct SetViewport;
impl crate::BidiCommand for SetViewport {
    const METHOD: &'static str = "browsingContext.setViewport";
    type Params = crate::browsing_context::SetViewportParameters;
    type Response = crate::browsing_context::SetViewportResult;
}

/// `browsingContext.startScreencast`
pub struct StartScreencast;
impl crate::BidiCommand for StartScreencast {
    const METHOD: &'static str = "browsingContext.startScreencast";
    type Params = crate::browsing_context::StartScreencastParameters;
    type Response = crate::browsing_context::StartScreencastResult;
}

/// `browsingContext.stopScreencast`
pub struct StopScreencast;
impl crate::BidiCommand for StopScreencast {
    const METHOD: &'static str = "browsingContext.stopScreencast";
    type Params = crate::browsing_context::StopScreencastParameters;
    type Response = crate::browsing_context::StopScreencastResult;
}

/// `browsingContext.traverseHistory`
pub struct TraverseHistory;
impl crate::BidiCommand for TraverseHistory {
    const METHOD: &'static str = "browsingContext.traverseHistory";
    type Params = crate::browsing_context::TraverseHistoryParameters;
    type Response = crate::browsing_context::TraverseHistoryResult;
}

/// `browsingContext.contextCreated`
pub struct ContextCreated;
impl crate::BidiEvent for ContextCreated {
    const METHOD: &'static str = "browsingContext.contextCreated";
    type Params = crate::browsing_context::ContextCreatedParameters;
}

/// `browsingContext.contextDestroyed`
pub struct ContextDestroyed;
impl crate::BidiEvent for ContextDestroyed {
    const METHOD: &'static str = "browsingContext.contextDestroyed";
    type Params = crate::browsing_context::Info;
}

/// `browsingContext.domContentLoaded`
pub struct DomContentLoaded;
impl crate::BidiEvent for DomContentLoaded {
    const METHOD: &'static str = "browsingContext.domContentLoaded";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.downloadEnd`
pub struct DownloadEnd;
impl crate::BidiEvent for DownloadEnd {
    const METHOD: &'static str = "browsingContext.downloadEnd";
    type Params = crate::browsing_context::DownloadEndParams;
}

/// `browsingContext.downloadWillBegin`
pub struct DownloadWillBegin;
impl crate::BidiEvent for DownloadWillBegin {
    const METHOD: &'static str = "browsingContext.downloadWillBegin";
    type Params = crate::browsing_context::DownloadWillBeginParams;
}

/// `browsingContext.fragmentNavigated`
pub struct FragmentNavigated;
impl crate::BidiEvent for FragmentNavigated {
    const METHOD: &'static str = "browsingContext.fragmentNavigated";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.historyUpdated`
pub struct HistoryUpdated;
impl crate::BidiEvent for HistoryUpdated {
    const METHOD: &'static str = "browsingContext.historyUpdated";
    type Params = crate::browsing_context::HistoryUpdatedParameters;
}

/// `browsingContext.load`
pub struct Load;
impl crate::BidiEvent for Load {
    const METHOD: &'static str = "browsingContext.load";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.navigationAborted`
pub struct NavigationAborted;
impl crate::BidiEvent for NavigationAborted {
    const METHOD: &'static str = "browsingContext.navigationAborted";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.navigationCommitted`
pub struct NavigationCommitted;
impl crate::BidiEvent for NavigationCommitted {
    const METHOD: &'static str = "browsingContext.navigationCommitted";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.navigationFailed`
pub struct NavigationFailed;
impl crate::BidiEvent for NavigationFailed {
    const METHOD: &'static str = "browsingContext.navigationFailed";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.navigationStarted`
pub struct NavigationStarted;
impl crate::BidiEvent for NavigationStarted {
    const METHOD: &'static str = "browsingContext.navigationStarted";
    type Params = crate::browsing_context::NavigationInfo;
}

/// `browsingContext.userPromptClosed`
pub struct UserPromptClosed;
impl crate::BidiEvent for UserPromptClosed {
    const METHOD: &'static str = "browsingContext.userPromptClosed";
    type Params = crate::browsing_context::UserPromptClosedParameters;
}

/// `browsingContext.userPromptOpened`
pub struct UserPromptOpened;
impl crate::BidiEvent for UserPromptOpened {
    const METHOD: &'static str = "browsingContext.userPromptOpened";
    type Params = crate::browsing_context::UserPromptOpenedParameters;
}

