// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `script.AddPreloadScriptParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddPreloadScriptParameters {
    #[serde(rename = "functionDeclaration")]
    pub function_declaration: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Vec<crate::script::ChannelValue>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<String>,
}

/// `script.AddPreloadScriptResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AddPreloadScriptResult {
    pub script: crate::script::PreloadScript,
}

/// `script.ArrayBufferRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArrayBufferRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.ArrayLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArrayLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::ListLocalValue,
}

/// `script.ArrayRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ArrayRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::ListRemoteValue>,
}

/// `script.AudioWorkletRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AudioWorkletRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.BaseRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BaseRealmInfo {
    pub realm: crate::script::Realm,
    pub origin: String,
}

/// `script.BigIntValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BigIntValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `script.BooleanValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BooleanValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: bool,
}

/// `script.CallFunctionParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct CallFunctionParameters {
    #[serde(rename = "functionDeclaration")]
    pub function_declaration: String,
    #[serde(rename = "awaitPromise")]
    pub await_promise: bool,
    pub target: crate::script::Target,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub arguments: Option<Vec<crate::script::LocalValue>>,
    #[serde(rename = "resultOwnership", skip_serializing_if = "Option::is_none")]
    pub result_ownership: Option<crate::script::ResultOwnership>,
    #[serde(rename = "serializationOptions", skip_serializing_if = "Option::is_none")]
    pub serialization_options: Option<crate::script::SerializationOptions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub this: Option<crate::script::LocalValue>,
    #[serde(rename = "userActivation", skip_serializing_if = "Option::is_none")]
    pub user_activation: Option<bool>,
}

/// `script.CallFunctionResult`
pub type CallFunctionResult = crate::script::EvaluateResult;

/// `script.Channel`
pub type Channel = String;

/// `script.ChannelProperties`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ChannelProperties {
    pub channel: crate::script::Channel,
    #[serde(rename = "serializationOptions", skip_serializing_if = "Option::is_none")]
    pub serialization_options: Option<crate::script::SerializationOptions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ownership: Option<crate::script::ResultOwnership>,
}

/// `script.ChannelValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ChannelValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::ChannelProperties,
}

/// `script.ContextTarget`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ContextTarget {
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<String>,
}

/// `script.DateLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DateLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `script.DateRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DateRemoteValue {
    #[serde(flatten)]
    pub date_local_value: crate::script::DateLocalValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.DedicatedWorkerRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DedicatedWorkerRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
    pub owners: Vec<crate::script::Realm>,
}

/// `script.DisownParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct DisownParameters {
    pub handles: Vec<crate::script::Handle>,
    pub target: crate::script::Target,
}

/// `script.DisownResult`
pub type DisownResult = crate::EmptyResult;

/// `script.ErrorRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ErrorRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.EvaluateParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EvaluateParameters {
    pub expression: String,
    pub target: crate::script::Target,
    #[serde(rename = "awaitPromise")]
    pub await_promise: bool,
    #[serde(rename = "resultOwnership", skip_serializing_if = "Option::is_none")]
    pub result_ownership: Option<crate::script::ResultOwnership>,
    #[serde(rename = "serializationOptions", skip_serializing_if = "Option::is_none")]
    pub serialization_options: Option<crate::script::SerializationOptions>,
    #[serde(rename = "userActivation", skip_serializing_if = "Option::is_none")]
    pub user_activation: Option<bool>,
}

/// `script.EvaluateResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum EvaluateResult {
    EvaluateResultSuccess(crate::script::EvaluateResultSuccess),
    EvaluateResultException(crate::script::EvaluateResultException),
}

/// `script.EvaluateResultException`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EvaluateResultException {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "exceptionDetails")]
    pub exception_details: crate::script::ExceptionDetails,
    pub realm: crate::script::Realm,
}

/// `script.EvaluateResultSuccess`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct EvaluateResultSuccess {
    #[serde(rename = "type")]
    pub type_: String,
    pub result: crate::script::RemoteValue,
    pub realm: crate::script::Realm,
}

/// `script.ExceptionDetails`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ExceptionDetails {
    #[serde(rename = "columnNumber")]
    pub column_number: u64,
    pub exception: crate::script::RemoteValue,
    #[serde(rename = "lineNumber")]
    pub line_number: u64,
    #[serde(rename = "stackTrace")]
    pub stack_trace: crate::script::StackTrace,
    pub text: String,
}

/// `script.FunctionRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct FunctionRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.GeneratorRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GeneratorRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.GetRealmsParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetRealmsParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<crate::browsing_context::BrowsingContext>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub type_: Option<crate::script::RealmType>,
}

/// `script.GetRealmsResult`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GetRealmsResult {
    pub realms: Vec<crate::script::RealmInfo>,
}

/// `script.HTMLCollectionRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HTMLCollectionRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::ListRemoteValue>,
}

/// `script.Handle`
pub type Handle = String;

/// `script.InternalId`
pub type InternalId = String;

/// `script.ListLocalValue`
pub type ListLocalValue = Vec<crate::script::LocalValue>;

/// `script.ListRemoteValue`
pub type ListRemoteValue = Vec<crate::script::RemoteValue>;

/// `script.LocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum LocalValue {
    RemoteReference(crate::script::RemoteReference),
    PrimitiveProtocolValue(crate::script::PrimitiveProtocolValue),
    ChannelValue(crate::script::ChannelValue),
    ArrayLocalValue(crate::script::ArrayLocalValue),
    MapLocalValue(crate::script::MapLocalValue),
    ObjectLocalValue(crate::script::ObjectLocalValue),
    SetLocalValue(crate::script::SetLocalValue),
}

/// `script.MapLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MapLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::MappingLocalValue,
}

/// `script.MapRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MapRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::MappingRemoteValue>,
}

/// `script.MappingLocalValue`
pub type MappingLocalValue = Vec<Vec<JsonValue>>;

/// `script.MappingRemoteValue`
pub type MappingRemoteValue = Vec<Vec<JsonValue>>;

/// `script.MessageParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MessageParameters {
    pub channel: crate::script::Channel,
    pub data: crate::script::RemoteValue,
    pub source: crate::script::Source,
}

/// `script.NodeListRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NodeListRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::ListRemoteValue>,
}

/// `script.NodeProperties`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NodeProperties {
    #[serde(rename = "nodeType")]
    pub node_type: u64,
    #[serde(rename = "childNodeCount")]
    pub child_node_count: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub attributes: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<crate::script::NodeRemoteValue>>,
    #[serde(rename = "localName", skip_serializing_if = "Option::is_none")]
    pub local_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<JsonValue>,
    #[serde(rename = "namespaceURI", skip_serializing_if = "Option::is_none")]
    pub namespace_uri: Option<String>,
    #[serde(rename = "nodeValue", skip_serializing_if = "Option::is_none")]
    pub node_value: Option<String>,
    #[serde(rename = "shadowRoot", skip_serializing_if = "Option::is_none")]
    pub shadow_root: Option<JsonValue>,
}

/// `script.NodeRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NodeRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(rename = "sharedId", skip_serializing_if = "Option::is_none")]
    pub shared_id: Option<crate::script::SharedId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::NodeProperties>,
}

/// `script.NullValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NullValue {
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.NumberValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NumberValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: JsonValue,
}

/// `script.ObjectLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ObjectLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::MappingLocalValue,
}

/// `script.ObjectRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ObjectRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::MappingRemoteValue>,
}

/// `script.PaintWorkletRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PaintWorkletRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.PreloadScript`
pub type PreloadScript = String;

/// `script.PrimitiveProtocolValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum PrimitiveProtocolValue {
    UndefinedValue(crate::script::UndefinedValue),
    NullValue(crate::script::NullValue),
    StringValue(crate::script::StringValue),
    NumberValue(crate::script::NumberValue),
    BooleanValue(crate::script::BooleanValue),
    BigIntValue(crate::script::BigIntValue),
}

/// `script.PromiseRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct PromiseRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.ProxyRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ProxyRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.Realm`
pub type Realm = String;

/// `script.RealmDestroyedParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RealmDestroyedParameters {
    pub realm: crate::script::Realm,
}

/// `script.RealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum RealmInfo {
    WindowRealmInfo(crate::script::WindowRealmInfo),
    DedicatedWorkerRealmInfo(crate::script::DedicatedWorkerRealmInfo),
    SharedWorkerRealmInfo(crate::script::SharedWorkerRealmInfo),
    ServiceWorkerRealmInfo(crate::script::ServiceWorkerRealmInfo),
    WorkerRealmInfo(crate::script::WorkerRealmInfo),
    PaintWorkletRealmInfo(crate::script::PaintWorkletRealmInfo),
    AudioWorkletRealmInfo(crate::script::AudioWorkletRealmInfo),
    WorkletRealmInfo(crate::script::WorkletRealmInfo),
}

/// `script.RealmTarget`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RealmTarget {
    pub realm: crate::script::Realm,
}

/// `script.RealmType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum RealmType {
    #[serde(rename = "window")]
    Window,
    #[serde(rename = "dedicated-worker")]
    DedicatedWorker,
    #[serde(rename = "shared-worker")]
    SharedWorker,
    #[serde(rename = "service-worker")]
    ServiceWorker,
    #[serde(rename = "worker")]
    Worker,
    #[serde(rename = "paint-worklet")]
    PaintWorklet,
    #[serde(rename = "audio-worklet")]
    AudioWorklet,
    #[serde(rename = "worklet")]
    Worklet,
}

/// `script.RegExpLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RegExpLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::RegExpValue,
}

/// `script.RegExpRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RegExpRemoteValue {
    #[serde(flatten)]
    pub reg_exp_local_value: crate::script::RegExpLocalValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.RegExpValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RegExpValue {
    pub pattern: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub flags: Option<String>,
}

/// `script.RemoteObjectReference`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RemoteObjectReference {
    pub handle: crate::script::Handle,
    #[serde(rename = "sharedId", skip_serializing_if = "Option::is_none")]
    pub shared_id: Option<crate::script::SharedId>,
}

/// `script.RemoteReference`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum RemoteReference {
    SharedReference(crate::script::SharedReference),
    RemoteObjectReference(crate::script::RemoteObjectReference),
}

/// `script.RemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum RemoteValue {
    PrimitiveProtocolValue(crate::script::PrimitiveProtocolValue),
    SymbolRemoteValue(crate::script::SymbolRemoteValue),
    ArrayRemoteValue(crate::script::ArrayRemoteValue),
    ObjectRemoteValue(crate::script::ObjectRemoteValue),
    FunctionRemoteValue(crate::script::FunctionRemoteValue),
    RegExpRemoteValue(crate::script::RegExpRemoteValue),
    DateRemoteValue(crate::script::DateRemoteValue),
    MapRemoteValue(crate::script::MapRemoteValue),
    SetRemoteValue(crate::script::SetRemoteValue),
    WeakMapRemoteValue(crate::script::WeakMapRemoteValue),
    WeakSetRemoteValue(crate::script::WeakSetRemoteValue),
    GeneratorRemoteValue(crate::script::GeneratorRemoteValue),
    ErrorRemoteValue(crate::script::ErrorRemoteValue),
    ProxyRemoteValue(crate::script::ProxyRemoteValue),
    PromiseRemoteValue(crate::script::PromiseRemoteValue),
    TypedArrayRemoteValue(crate::script::TypedArrayRemoteValue),
    ArrayBufferRemoteValue(crate::script::ArrayBufferRemoteValue),
    NodeListRemoteValue(crate::script::NodeListRemoteValue),
    HTMLCollectionRemoteValue(crate::script::HTMLCollectionRemoteValue),
    NodeRemoteValue(crate::script::NodeRemoteValue),
    WindowProxyRemoteValue(crate::script::WindowProxyRemoteValue),
}

/// `script.RemovePreloadScriptParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct RemovePreloadScriptParameters {
    pub script: crate::script::PreloadScript,
}

/// `script.RemovePreloadScriptResult`
pub type RemovePreloadScriptResult = crate::EmptyResult;

/// `script.ResultOwnership`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ResultOwnership {
    #[serde(rename = "root")]
    Root,
    #[serde(rename = "none")]
    None,
}

/// `script.SerializationOptions`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SerializationOptions {
    #[serde(rename = "maxDomDepth", skip_serializing_if = "Option::is_none")]
    pub max_dom_depth: Option<JsonValue>,
    #[serde(rename = "maxObjectDepth", skip_serializing_if = "Option::is_none")]
    pub max_object_depth: Option<JsonValue>,
    #[serde(rename = "includeShadowTree", skip_serializing_if = "Option::is_none")]
    pub include_shadow_tree: Option<JsonValue>,
}

/// `script.ServiceWorkerRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ServiceWorkerRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.SetLocalValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetLocalValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::ListLocalValue,
}

/// `script.SetRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<crate::script::ListRemoteValue>,
}

/// `script.SharedId`
pub type SharedId = String;

/// `script.SharedReference`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SharedReference {
    #[serde(rename = "sharedId")]
    pub shared_id: crate::script::SharedId,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
}

/// `script.SharedWorkerRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SharedWorkerRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.Source`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Source {
    pub realm: crate::script::Realm,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub context: Option<crate::browsing_context::BrowsingContext>,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
}

/// `script.SpecialNumber`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum SpecialNumber {
    #[serde(rename = "NaN")]
    NaN,
    #[serde(rename = "-0")]
    N0,
    #[serde(rename = "Infinity")]
    Infinity,
    #[serde(rename = "-Infinity")]
    InfinityAlt,
}

/// `script.StackFrame`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StackFrame {
    #[serde(rename = "columnNumber")]
    pub column_number: u64,
    #[serde(rename = "functionName")]
    pub function_name: String,
    #[serde(rename = "lineNumber")]
    pub line_number: u64,
    pub url: String,
}

/// `script.StackTrace`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StackTrace {
    #[serde(rename = "callFrames")]
    pub call_frames: Vec<crate::script::StackFrame>,
}

/// `script.StringValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct StringValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: String,
}

/// `script.SymbolRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SymbolRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.Target`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum Target {
    ContextTarget(crate::script::ContextTarget),
    RealmTarget(crate::script::RealmTarget),
}

/// `script.TypedArrayRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct TypedArrayRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.UndefinedValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct UndefinedValue {
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.WeakMapRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WeakMapRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.WeakSetRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WeakSetRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.WindowProxyProperties`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WindowProxyProperties {
    pub context: crate::browsing_context::BrowsingContext,
}

/// `script.WindowProxyRemoteValue`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WindowProxyRemoteValue {
    #[serde(rename = "type")]
    pub type_: String,
    pub value: crate::script::WindowProxyProperties,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub handle: Option<crate::script::Handle>,
    #[serde(rename = "internalId", skip_serializing_if = "Option::is_none")]
    pub internal_id: Option<crate::script::InternalId>,
}

/// `script.WindowRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WindowRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
    pub context: crate::browsing_context::BrowsingContext,
    #[serde(rename = "userContext", skip_serializing_if = "Option::is_none")]
    pub user_context: Option<crate::browser::UserContext>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sandbox: Option<String>,
}

/// `script.WorkerRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WorkerRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.WorkletRealmInfo`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct WorkletRealmInfo {
    #[serde(flatten)]
    pub base_realm_info: crate::script::BaseRealmInfo,
    #[serde(rename = "type")]
    pub type_: String,
}

/// `script.addPreloadScript`
pub struct AddPreloadScript;
impl crate::BidiCommand for AddPreloadScript {
    const METHOD: &'static str = "script.addPreloadScript";
    type Params = crate::script::AddPreloadScriptParameters;
    type Response = crate::script::AddPreloadScriptResult;
}

/// `script.callFunction`
pub struct CallFunction;
impl crate::BidiCommand for CallFunction {
    const METHOD: &'static str = "script.callFunction";
    type Params = crate::script::CallFunctionParameters;
    type Response = crate::script::CallFunctionResult;
}

/// `script.disown`
pub struct Disown;
impl crate::BidiCommand for Disown {
    const METHOD: &'static str = "script.disown";
    type Params = crate::script::DisownParameters;
    type Response = crate::script::DisownResult;
}

/// `script.evaluate`
pub struct Evaluate;
impl crate::BidiCommand for Evaluate {
    const METHOD: &'static str = "script.evaluate";
    type Params = crate::script::EvaluateParameters;
    type Response = crate::script::EvaluateResult;
}

/// `script.getRealms`
pub struct GetRealms;
impl crate::BidiCommand for GetRealms {
    const METHOD: &'static str = "script.getRealms";
    type Params = crate::script::GetRealmsParameters;
    type Response = crate::script::GetRealmsResult;
}

/// `script.removePreloadScript`
pub struct RemovePreloadScript;
impl crate::BidiCommand for RemovePreloadScript {
    const METHOD: &'static str = "script.removePreloadScript";
    type Params = crate::script::RemovePreloadScriptParameters;
    type Response = crate::script::RemovePreloadScriptResult;
}

/// `script.realmCreated`
pub struct RealmCreated;
impl crate::BidiEvent for RealmCreated {
    const METHOD: &'static str = "script.realmCreated";
    type Params = crate::script::RealmInfo;
}

/// `script.realmDestroyed`
pub struct RealmDestroyed;
impl crate::BidiEvent for RealmDestroyed {
    const METHOD: &'static str = "script.realmDestroyed";
    type Params = crate::script::RealmDestroyedParameters;
}

