#!/usr/bin/env python3
"""Bump the xcelerate version across every manifest in one shot.

Usage::

    python scripts/bump_version.py 0.1.7

The Rust workspace version lives in the root ``Cargo.toml``; every crate inherits
it via ``version.workspace = true``. The language bindings are regenerated by the
``generate_*`` scripts (which read the workspace version), so only their static
manifest files need updating here.
"""

from __future__ import annotations

import os
import re
import sys

from common import ROOT, log


def update_file(path, pattern, replacement):
    if not os.path.exists(path):
        log("WARNING", f"file not found: {path}")
        return
    with open(path, "r", encoding="utf-8") as handle:
        content = handle.read()
    new_content = re.sub(pattern, replacement, content, flags=re.MULTILINE)
    if new_content != content:
        with open(path, "w", encoding="utf-8", newline="") as handle:
            handle.write(new_content)
        log("UPDATE", path)
    else:
        log("SKIP", f"{path} (no change)")


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/bump_version.py <new_version>")
        print("Example: python scripts/bump_version.py 0.1.7")
        return 1

    version = sys.argv[1]
    print(f"=== Bumping Xcelerate to version {version} ===")

    update_file(
        os.path.join(ROOT, "Cargo.toml"),
        r'^version = "[^"]+"',
        f'version = "{version}"',
    )
    # Internal crate pins in [workspace.dependencies].
    for internal in ("xcelerate-core", "xcelerate-stealth"):
        update_file(
            os.path.join(ROOT, "Cargo.toml"),
            rf'({internal} = \{{ path = "crates/{internal}", version = )"[^"]+"',
            rf'\g<1>"{version}"',
        )
    update_file(
        os.path.join(ROOT, "README.md"),
        r'xcelerate = "[^"]+"',
        f'xcelerate = "{version}"',
    )
    update_file(
        os.path.join(ROOT, "bindings", "javascript", "package.json"),
        r'"version": "[^"]+"',
        f'"version": "{version}"',
    )
    update_file(
        os.path.join(ROOT, "bindings", "python", "pyproject.toml"),
        r'^version = "[^"]+"',
        f'version = "{version}"',
    )
    update_file(
        os.path.join(ROOT, "bindings", "csharp", "Xcelerate.CSharp.csproj"),
        r"<Version>[^<]+</Version>",
        f"<Version>{version}</Version>",
    )
    for jvm_binding in ("kotlin", "java"):
        update_file(
            os.path.join(ROOT, "bindings", jvm_binding, "build.gradle.kts"),
            r'^version = "[^"]+"',
            f'version = "{version}"',
        )

    print("=== Done ===")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
