#!/usr/bin/env python3
"""Generate the Ruby bindings (uniffi) and assemble a gem.

Ruby is a built-in UniFFI target. The generator emits a single ``xcelerate.rb``;
this script places it under ``lib/`` (the conventional gem layout), writes a
gemspec, and copies the native library for the host platform.

Building/pushing the gem needs Ruby (``ruby``/``gem`` on ``PATH``); the script
skips the build with a hint if it is missing.
"""

from __future__ import annotations

import os
import shutil

from common import ROOT, find_tool, log, run_checked, uniffi_bindgen, workspace_version

NATIVE_LIBS = ("xcelerate.dll", "libxcelerate.so", "libxcelerate.dylib")

GEMSPEC = """\
# Generated by scripts/generate_ruby_bindings.py - edit the script, not this.
Gem::Specification.new do |spec|
  spec.name          = "xcelerate"
  spec.version       = "@VERSION@"
  spec.summary       = "Chrome DevTools Protocol client for Ruby (xcelerate core)."
  spec.description   = "Ruby bindings for the xcelerate CDP engine, generated with UniFFI."
  spec.authors       = ["AzzoDude"]
  spec.homepage      = "https://github.com/AzzoDude/xcelerate"
  spec.license       = "MIT"
  spec.required_ruby_version = ">= 3.1"

  spec.files = Dir["lib/**/*.rb", "*.dll", "*.so", "*.dylib"]
  spec.require_paths = ["lib"]
  spec.add_dependency "ffi", "~> 1.15"
end
"""


def main():
    ruby_dir = os.path.join(ROOT, "bindings", "ruby")
    lib_dir = os.path.join(ruby_dir, "lib")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Ruby Bindings ---")
    os.makedirs(lib_dir, exist_ok=True)

    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    print("--- 1. Generating Ruby sources with UniFFI ---")
    stale = os.path.join(lib_dir, "xcelerate.rb")
    if os.path.exists(stale):
        os.remove(stale)
    run_checked(
        uniffi_bindgen()
        + [
            "generate",
            "--library",
            built_dll,
            "--language",
            "ruby",
            "--out-dir",
            lib_dir,
            "--no-format",
        ],
        cwd=ROOT,
    )

    _write(
        os.path.join(ruby_dir, "xcelerate.gemspec"),
        GEMSPEC.replace("@VERSION@", workspace_version()),
    )
    log("WRITE", "xcelerate.gemspec")

    print("--- 2. Distributing native libraries ---")
    for lib in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", lib)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(ruby_dir, lib))
            log("COPY", f"{lib} -> {ruby_dir}")

    print("--- 3. Validating the gem ---")
    ruby = find_tool("ruby")
    if not os.path.exists(ruby):
        log("WARNING", "ruby not found; sources generated only")
        log("HINT", "install Ruby 3.1+ (ruby-lang.org or your package manager)")
        return 0
    run_checked([ruby, "-c", os.path.join(lib_dir, "xcelerate.rb")])
    log("SUCCESS", f"Ruby bindings ready in {ruby_dir}")
    return 0


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


if __name__ == "__main__":
    raise SystemExit(main())
