#!/usr/bin/env python3
"""Generate the Swift bindings (uniffi) and assemble a SwiftPM package.

Swift is a built-in UniFFI target. The generator emits a Swift module plus a C
header/modulemap for the low-level FFI; this script arranges them into a SwiftPM
package layout (``Sources/Xcelerate`` + ``Sources/xcelerateFFI``) and copies the
native library for the host platform.

Building the package needs a Swift toolchain (``swift`` on ``PATH``); the script
skips the build with a hint if it is missing.
"""

from __future__ import annotations

import os
import shutil

from common import ROOT, find_tool, log, run_checked, uniffi_bindgen, workspace_version

NATIVE_LIBS = ("xcelerate.dll", "libxcelerate.so", "libxcelerate.dylib")

PACKAGE_SWIFT = """\
// swift-tools-version:5.9
// Generated by scripts/generate_swift_bindings.py - edit the script, not this.
import PackageDescription

let package = Package(
    name: "Xcelerate",
    platforms: [.macOS(.v12)],
    products: [
        .library(name: "Xcelerate", targets: ["Xcelerate"]),
    ],
    targets: [
        // The generated C header + modulemap for the low-level FFI.
        .systemLibrary(name: "xcelerateFFI", path: "Sources/xcelerateFFI"),
        // The generated Swift API.
        .target(
            name: "Xcelerate",
            dependencies: ["xcelerateFFI"],
            path: "Sources/Xcelerate"
        ),
    ]
)
"""


def main():
    swift_dir = os.path.join(ROOT, "bindings", "swift")
    api_dir = os.path.join(swift_dir, "Sources", "Xcelerate")
    ffi_dir = os.path.join(swift_dir, "Sources", "xcelerateFFI")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Swift Bindings ---")

    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    # Regenerate from scratch but never delete hand-authored package metadata.
    for directory in (api_dir, ffi_dir):
        if os.path.isdir(directory):
            shutil.rmtree(directory)
        os.makedirs(directory, exist_ok=True)

    print("--- 1. Generating Swift sources with UniFFI ---")
    run_checked(
        uniffi_bindgen()
        + [
            "generate",
            "--library",
            built_dll,
            "--language",
            "swift",
            "--out-dir",
            swift_dir,
            "--no-format",
        ],
        cwd=ROOT,
    )

    # Arrange the generated files into the package layout.
    generated_api = os.path.join(swift_dir, "xcelerate.swift")
    header = os.path.join(swift_dir, "xcelerateFFI.h")
    modulemap = os.path.join(swift_dir, "xcelerateFFI.modulemap")
    if os.path.exists(generated_api):
        shutil.move(generated_api, os.path.join(api_dir, "xcelerate.swift"))
    if os.path.exists(header):
        shutil.move(header, os.path.join(ffi_dir, "xcelerateFFI.h"))
    if os.path.exists(modulemap):
        # SwiftPM's systemLibrary target expects `module.modulemap`.
        shutil.move(modulemap, os.path.join(ffi_dir, "module.modulemap"))

    _write(os.path.join(swift_dir, "Package.swift"), PACKAGE_SWIFT)
    log("WRITE", "Package.swift")

    print("--- 2. Distributing native libraries ---")
    for lib in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", lib)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(swift_dir, lib))
            log("COPY", f"{lib} -> {swift_dir}")

    print("--- 3. Building Swift package ---")
    swift = find_tool("swift")
    if not os.path.exists(swift):
        log("WARNING", "swift not found; sources generated only")
        log("HINT", "install the Swift toolchain (macOS: Xcode, Windows/Linux: swift.org)")
        return 0
    run_checked([swift, "build"], cwd=swift_dir)
    log("SUCCESS", f"Swift bindings ready in {swift_dir}")
    return 0


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


if __name__ == "__main__":
    raise SystemExit(main())
