#!/usr/bin/env python3
"""Generate the Dart/Flutter bindings and assemble a pub package.

Dart is not a built-in UniFFI target; it needs the third-party
``uniffi-bindgen-dart`` generator (``cargo install uniffi-bindgen-dart``). The
generator emits a single ``xcelerate.dart`` which loads the native library named
``uniffi_xcelerate`` (``uniffi_xcelerate.dll`` / ``libuniffi_xcelerate.so`` /
``libuniffi_xcelerate.dylib``); this script places it under ``lib/``, writes a
``pubspec.yaml``, and copies the native library under that name.

Building/analyzing needs the Dart SDK (``dart``/``flutter`` on ``PATH``); the
script skips with a hint if it is missing.
"""

from __future__ import annotations

import os
import shutil

from common import ROOT, find_tool, log, run_checked, workspace_version

# (source name in target/release, destination name for Dart FFI)
NATIVE_LIBS = (
    ("xcelerate.dll", "uniffi_xcelerate.dll"),
    ("libxcelerate.so", "libuniffi_xcelerate.so"),
    ("libxcelerate.dylib", "libuniffi_xcelerate.dylib"),
)


def pubspec(version: str) -> str:
    return f"""\
# Generated by scripts/generate_dart_bindings.py - edit the script, not this.
name: xcelerate
description: Chrome DevTools Protocol client for Dart/Flutter, backed by the xcelerate Rust core.
version: {version}
homepage: https://github.com/AzzoDude/xcelerate
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  ffi: ^2.1.0
"""


def bindgen_tool() -> str | None:
    found = find_tool("uniffi-bindgen-dart")
    return found if os.path.exists(found) else None


def main():
    dart_dir = os.path.join(ROOT, "bindings", "dart")
    lib_dir = os.path.join(dart_dir, "lib")
    src_dir = os.path.join(dart_dir, "src")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Dart Bindings ---")
    os.makedirs(lib_dir, exist_ok=True)
    os.makedirs(src_dir, exist_ok=True)

    tool = bindgen_tool()
    if not tool:
        log("WARNING", "uniffi-bindgen-dart not found; skipping Dart generation")
        log("HINT", "run `cargo install uniffi-bindgen-dart` to install it")
        return 0

    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    print("--- 1. Generating Dart sources ---")
    stale = os.path.join(lib_dir, "xcelerate.dart")
    if os.path.exists(stale):
        os.remove(stale)
    run_checked(
        [tool, "generate", "--out-dir", lib_dir, "--no-format", built_dll],
        cwd=ROOT,
    )

    _write(os.path.join(dart_dir, "pubspec.yaml"), pubspec(workspace_version()))
    log("WRITE", "pubspec.yaml")

    print("--- 2. Distributing native libraries ---")
    for source, destination in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", source)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(src_dir, destination))
            log("COPY", f"{source} -> src/{destination}")

    print("--- 3. Analyzing the package ---")
    dart = find_tool("dart")
    if not os.path.exists(dart):
        log("WARNING", "dart not found; sources generated only")
        log("HINT", "install the Dart SDK or Flutter (dart.dev)")
        return 0
    run_checked([dart, "pub", "get"], cwd=dart_dir)
    run_checked([dart, "analyze"], cwd=dart_dir)
    log("SUCCESS", f"Dart bindings ready in {dart_dir}")
    return 0


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


if __name__ == "__main__":
    raise SystemExit(main())
