#!/usr/bin/env python3
"""Generate the Kotlin bindings (uniffi) and assemble a Gradle JVM library.

Kotlin is a first-class UniFFI target, so the bundled ``uniffi-bindgen`` helper
produces the sources. The generated code depends on JNA (the FFI layer) and
kotlinx-coroutines (the suspend/async surface); both are declared in the Gradle
build that is written next to the sources.
"""

from __future__ import annotations

import os
import re
import shutil

from common import (
    BINDINGS_DIR,
    ROOT,
    gradle_tool,
    jvm_env,
    log,
    run_checked,
    uniffi_bindgen,
    workspace_version,
)

NATIVE_LIBS = ("xcelerate.dll", "libxcelerate.so", "libxcelerate.dylib")

SETTINGS_GRADLE = 'rootProject.name = "xcelerate"\n'

GRADLE_PROPERTIES = "org.gradle.jvmargs=-Xmx1g\norg.gradle.caching=true\n"

GITIGNORE = ".gradle/\n.kotlin/\nbuild/\n"

BUILD_GRADLE = """\
// Generated by scripts/generate_kotlin_bindings.py - edit the script, not this.
plugins {
    kotlin("jvm") version "2.1.0"
    `java-library`
    `maven-publish`
    `signing`
}

group = "io.github.azzodude"
version = "@VERSION@"

repositories {
    mavenCentral()
}

dependencies {
    // The generated bindings use JNA for the FFI and kotlinx-coroutines for the
    // suspend/asynchronous API surface.
    api("net.java.dev.jna:jna:5.16.0")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1")
}

java {
    withSourcesJar()
    withJavadocJar()
}

// Generated doc comments contain raw HTML (e.g. `<input>`), which the strict
// doclint checker rejects; disable it so the javadoc jar builds.
tasks.withType<Javadoc>().configureEach {
    (options as org.gradle.external.javadoc.StandardJavadocDocletOptions)
        .addBooleanOption("Xdoclint:none", true)
}

// Bundle the native core in the jar so consumers can extract it and point the
// loader at it with -Duniffi.component.xcelerate.libraryOverride=<abs path>.
tasks.processResources {
    from(rootDir) {
        include("*.dll", "*.so", "*.dylib")
        into("uniffi/xcelerate")
    }
}

// Resolve credentials from (in order) a -P/Gradle property, an environment
// variable, then the nearest .env file. Never commit real secrets.
val dotenv: Map<String, String> = generateSequence(projectDir) { it.parentFile }
    .map { it.resolve(".env") }
    .firstOrNull { it.isFile }
    ?.readLines()
    ?.mapNotNull { line ->
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed.startsWith("#") || !trimmed.contains("=")) null
        else trimmed.substringBefore("=").trim() to trimmed.substringAfter("=").trim().trim('"')
    }?.toMap() ?: emptyMap()

fun secret(name: String): String? =
    providers.gradleProperty(name).orNull
        ?: providers.environmentVariable(name).orNull
        ?: dotenv[name]

signing {
    val inline = secret("signingKey")
    val keyFile = secret("signingKeyFile")
    val password = secret("signingPassword")
    when {
        inline != null && password != null -> useInMemoryPgpKeys(inline, password)
        keyFile != null && password != null -> useInMemoryPgpKeys(file(keyFile).readText(), password)
        else -> useGpgCmd()
    }
    sign(publishing.publications)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "xcelerate"
            pom {
                name.set("Xcelerate Kotlin SDK")
                description.set("Kotlin/JVM bindings for the xcelerate CDP engine.")
                url.set("https://github.com/AzzoDude/xcelerate")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("AzzoDude")
                        url.set("https://github.com/AzzoDude")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/AzzoDude/xcelerate.git")
                    developerConnection.set("scm:git:ssh://git@github.com/AzzoDude/xcelerate.git")
                    url.set("https://github.com/AzzoDude/xcelerate")
                }
            }
        }
    }
    repositories {
        maven {
            name = "central"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
            credentials {
                username = secret("centralUsername")
                password = secret("centralPassword")
            }
        }
    }
}
"""


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


def _patch_defaults(content):
    """Give the generated ``BrowserConfig`` (and ``launch``) Kotlin defaults.

    UniFFI emits required positional fields, so ``BrowserConfig()`` would not
    compile without them. The exact spacing of the generated ``data class`` is
    stable per UniFFI release; these regexes only add a default when one is not
    already present.
    """
    edits = (
        (r"var `headless`: kotlin\.Boolean(?!\s*=)", "var `headless`: kotlin.Boolean = true"),
        (r"var `detached`: kotlin\.Boolean(?!\s*=)", "var `detached`: kotlin.Boolean = true"),
        (r"var `executablePath`: kotlin\.String\?(?!\s*=)", "var `executablePath`: kotlin.String? = null"),
        (
            r"var `plugins`: List<kotlin\.String>\?(?!\s*=)",
            "var `plugins`: List<kotlin.String>? = null",
        ),
        (r"(suspend fun `launch`\(`config`: BrowserConfig)\)", r"\1 = BrowserConfig())"),
    )
    for pattern, replacement in edits:
        content, count = re.subn(pattern, replacement, content)
        if count == 0:
            log("WARNING", f"Kotlin default patch did not match: {pattern}")
    return content


def main():
    kotlin_dir = os.path.join(BINDINGS_DIR, "kotlin")
    src_dir = os.path.join(kotlin_dir, "src", "main", "kotlin")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Kotlin Bindings ---")
    os.makedirs(kotlin_dir, exist_ok=True)

    print("--- 0. Building Rust library (cdylib) ---")
    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    print("--- 1. Generating Kotlin sources with UniFFI ---")
    if os.path.isdir(src_dir):
        shutil.rmtree(src_dir)
    os.makedirs(src_dir, exist_ok=True)
    config = os.path.join(ROOT, "scripts", "uniffi-kotlin.toml")
    run_checked(
        uniffi_bindgen()
        + [
            "generate",
            "--library",
            built_dll,
            "--language",
            "kotlin",
            "--no-format",
            "-c",
            config,
            "--out-dir",
            src_dir,
        ],
        cwd=ROOT,
    )

    generated = os.path.join(src_dir, "uniffi", "xcelerate", "xcelerate.kt")
    if os.path.exists(generated):
        with open(generated, "r", encoding="utf-8") as handle:
            content = _patch_defaults(handle.read())
        _write(generated, content)
        log("PATCH", "BrowserConfig defaults + launch() default applied")

    print("--- 2. Distributing native libraries ---")
    for lib in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", lib)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(kotlin_dir, lib))
            log("COPY", f"{lib} -> {kotlin_dir}")

    print("--- 3. Writing Gradle build ---")
    _write(os.path.join(kotlin_dir, "settings.gradle.kts"), SETTINGS_GRADLE)
    _write(os.path.join(kotlin_dir, "gradle.properties"), GRADLE_PROPERTIES)
    _write(os.path.join(kotlin_dir, ".gitignore"), GITIGNORE)
    _write(
        os.path.join(kotlin_dir, "build.gradle.kts"),
        BUILD_GRADLE.replace("@VERSION@", workspace_version()),
    )

    gradle = gradle_tool()
    if not gradle:
        log("SKIP", "gradle not found (see scripts/install_toolchains.py); sources generated only")
        return 0

    print("--- 4. Building Kotlin library (gradle) ---")
    run_checked([gradle, "build", "-x", "test", "--no-daemon"], cwd=kotlin_dir, env=jvm_env())
    log("SUCCESS", f"Kotlin bindings ready in {kotlin_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
