#!/usr/bin/env python3
"""Generate the Go bindings and assemble a Go module.

Go is not a built-in UniFFI target. It needs the third-party
``uniffi-bindgen-go`` generator, which is **not** on crates.io - install it with
the Go toolchain:

    go install github.com/NordSecurity/uniffi-bindgen-go/v2/uniffi-bindgen-go@latest

The generator emits a Go package that cgo-links the native library. This script
runs it, copies the native library for the host platform, and writes a ``go.mod``.

Building needs the Go toolchain (``go`` on ``PATH``); the script skips with a
hint if either the generator or Go is missing.
"""

from __future__ import annotations

import os
import shutil

from common import ROOT, find_tool, log, run_checked, workspace_version

NATIVE_LIBS = ("xcelerate.dll", "libxcelerate.so", "libxcelerate.dylib")

GO_MOD = """\
// Generated by scripts/generate_go_bindings.py - edit the script, not this.
module github.com/AzzoDude/xcelerate/go

go 1.21
"""


def main():
    go_dir = os.path.join(ROOT, "bindings", "go")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Go Bindings ---")
    os.makedirs(go_dir, exist_ok=True)

    tool = find_tool("uniffi-bindgen-go")
    if not os.path.exists(tool):
        log("WARNING", "uniffi-bindgen-go not found; skipping Go generation")
        log(
            "HINT",
            "run `go install github.com/NordSecurity/uniffi-bindgen-go/v2/uniffi-bindgen-go@latest`",
        )
        return 0

    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    print("--- 1. Generating Go sources ---")
    run_checked(
        [tool, "generate", "--library", built_dll, "--out-dir", go_dir],
        cwd=ROOT,
    )

    _write(os.path.join(go_dir, "go.mod"), GO_MOD)
    log("WRITE", "go.mod")

    print("--- 2. Distributing native libraries ---")
    for lib in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", lib)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(go_dir, lib))
            log("COPY", f"{lib} -> {go_dir}")

    print("--- 3. Building the Go package ---")
    go = find_tool("go")
    if not os.path.exists(go):
        log("WARNING", "go not found; sources generated only")
        log("HINT", "install the Go toolchain (go.dev/dl)")
        return 0
    run_checked([go, "build", "./..."], cwd=go_dir)
    log("SUCCESS", f"Go bindings ready in {go_dir}")
    return 0


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


if __name__ == "__main__":
    raise SystemExit(main())
