#!/usr/bin/env python3
"""Generate the Java bindings (uniffi) and assemble a Gradle JVM library.

Java is not a built-in UniFFI target; it needs the external
``uniffi-bindgen-java`` generator (IronCoreLabs). Version ``0.4.2`` is the
release that targets UniFFI ``0.31`` - the same metadata version as the Rust
core - so keep the two in step.

The generated code uses Java's Foreign Function & Memory API (Project Panama),
so it has **no external runtime dependencies** and requires **Java 22+**.
Install the toolchain with ``python scripts/install_toolchains.py``.
"""

from __future__ import annotations

import os
import shutil

from common import (
    BINDINGS_DIR,
    ROOT,
    find_tool,
    gradle_tool,
    jvm_env,
    log,
    run_checked,
    workspace_version,
)

NATIVE_LIBS = ("xcelerate.dll", "libxcelerate.so", "libxcelerate.dylib")
JAVA_BINDGEN = "uniffi-bindgen-java"

SETTINGS_GRADLE = 'rootProject.name = "xcelerate"\n'

GRADLE_PROPERTIES = "org.gradle.jvmargs=-Xmx1g\norg.gradle.caching=true\n"

GITIGNORE = ".gradle/\n.kotlin/\nbuild/\n"

BUILD_GRADLE = """\
// Generated by scripts/generate_java_bindings.py - edit the script, not this.
plugins {
    `java-library`
    `maven-publish`
    `signing`
}

group = "io.github.azzodude"
version = "@VERSION@"

repositories {
    mavenCentral()
}

java {
    withSourcesJar()
    withJavadocJar()
}

// Generated doc comments contain raw HTML (e.g. `<input>`), which the strict
// doclint checker rejects; disable it so the javadoc jar builds.
tasks.withType<Javadoc>().configureEach {
    (options as org.gradle.external.javadoc.StandardJavadocDocletOptions)
        .addBooleanOption("Xdoclint:none", true)
}

tasks.withType<JavaCompile>().configureEach {
    // The bindings use the Foreign Function & Memory API, finalized in Java 22.
    options.release = 22
}

// Bundle the native core in the jar so consumers can extract it and point the
// loader at it with -Duniffi.component.xcelerate.libraryOverride=<abs path>.
tasks.processResources {
    from(rootDir) {
        include("*.dll", "*.so", "*.dylib")
        into("uniffi/xcelerate")
    }
}

// Resolve credentials from (in order) a -P/Gradle property, an environment
// variable, then the nearest .env file. Never commit real secrets.
val dotenv: Map<String, String> = generateSequence(projectDir) { it.parentFile }
    .map { it.resolve(".env") }
    .firstOrNull { it.isFile }
    ?.readLines()
    ?.mapNotNull { line ->
        val trimmed = line.trim()
        if (trimmed.isEmpty() || trimmed.startsWith("#") || !trimmed.contains("=")) null
        else trimmed.substringBefore("=").trim() to trimmed.substringAfter("=").trim().trim('"')
    }?.toMap() ?: emptyMap()

fun secret(name: String): String? =
    providers.gradleProperty(name).orNull
        ?: providers.environmentVariable(name).orNull
        ?: dotenv[name]

signing {
    val inline = secret("signingKey")
    val keyFile = secret("signingKeyFile")
    val password = secret("signingPassword")
    when {
        inline != null && password != null -> useInMemoryPgpKeys(inline, password)
        keyFile != null && password != null -> useInMemoryPgpKeys(file(keyFile).readText(), password)
        else -> useGpgCmd()
    }
    sign(publishing.publications)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "xcelerate-java"
            pom {
                name.set("Xcelerate Java SDK")
                description.set("Java/JVM bindings for the xcelerate CDP engine.")
                url.set("https://github.com/AzzoDude/xcelerate")
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("AzzoDude")
                        url.set("https://github.com/AzzoDude")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/AzzoDude/xcelerate.git")
                    developerConnection.set("scm:git:ssh://git@github.com/AzzoDude/xcelerate.git")
                    url.set("https://github.com/AzzoDude/xcelerate")
                }
            }
        }
    }
    repositories {
        maven {
            name = "central"
            url = uri("https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/")
            credentials {
                username = secret("centralUsername")
                password = secret("centralPassword")
            }
        }
    }
}
"""


def _write(path, content):
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


def _tool(name):
    found = find_tool(name)
    return found if os.path.exists(found) else None


def main():
    java_dir = os.path.join(BINDINGS_DIR, "java")
    src_dir = os.path.join(java_dir, "src", "main", "java")
    built_dll = os.path.join(ROOT, "target", "release", "xcelerate.dll")

    print("--- Phase: Generating Java Bindings ---")
    os.makedirs(java_dir, exist_ok=True)

    tool = _tool(JAVA_BINDGEN)
    if not tool:
        log("WARNING", f"{JAVA_BINDGEN} not found; skipping Java generation")
        log("HINT", "run `python scripts/install_toolchains.py` to install it via cargo")
        return 0

    print("--- 0. Building Rust library (cdylib) ---")
    if os.environ.get("SKIP_RUST_BUILD") == "true" and os.path.exists(built_dll):
        log("SKIP", f"Rust build skipped, using existing: {built_dll}")
    else:
        run_checked(["cargo", "build", "--release"], cwd=ROOT)

    print("--- 1. Generating Java sources with uniffi-bindgen-java ---")
    if os.path.isdir(src_dir):
        shutil.rmtree(src_dir)
    os.makedirs(src_dir, exist_ok=True)
    config = os.path.join(ROOT, "scripts", "uniffi-java.toml")
    run_checked(
        [tool, "generate", "-c", config, "--out-dir", src_dir, built_dll], cwd=ROOT
    )

    print("--- 2. Distributing native libraries ---")
    for lib in NATIVE_LIBS:
        src = os.path.join(ROOT, "target", "release", lib)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(java_dir, lib))
            log("COPY", f"{lib} -> {java_dir}")

    print("--- 3. Writing Gradle build ---")
    _write(os.path.join(java_dir, "settings.gradle.kts"), SETTINGS_GRADLE)
    _write(os.path.join(java_dir, "gradle.properties"), GRADLE_PROPERTIES)
    _write(os.path.join(java_dir, ".gitignore"), GITIGNORE)
    _write(
        os.path.join(java_dir, "build.gradle.kts"),
        BUILD_GRADLE.replace("@VERSION@", workspace_version()),
    )

    gradle = gradle_tool()
    if not gradle:
        log("SKIP", "gradle not found (see scripts/install_toolchains.py); sources generated only")
        return 0

    print("--- 4. Building Java library (gradle) ---")
    run_checked([gradle, "build", "-x", "test", "--no-daemon"], cwd=java_dir, env=jvm_env())
    log("SUCCESS", f"Java bindings ready in {java_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
