// @generated by scripts/generate_rust_code.py -- do not edit by hand.
#![allow(non_snake_case, unused_imports, dead_code, clippy::all)]

use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use crate::{BidiCommand, BidiEvent};

/// `emulation.ForcedColorsModeTheme`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ForcedColorsModeTheme {
    #[serde(rename = "light")]
    Light,
    #[serde(rename = "dark")]
    Dark,
}

/// `emulation.GeolocationCoordinates`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GeolocationCoordinates {
    pub latitude: f64,
    pub longitude: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accuracy: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub altitude: Option<JsonValue>,
    #[serde(rename = "altitudeAccuracy", skip_serializing_if = "Option::is_none")]
    pub altitude_accuracy: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub heading: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub speed: Option<JsonValue>,
}

/// `emulation.GeolocationPositionError`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct GeolocationPositionError {
    #[serde(rename = "type")]
    pub type_: String,
}

/// `emulation.MediaFeatures`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct MediaFeatures {
    #[serde(rename = "any-hover", skip_serializing_if = "Option::is_none")]
    pub any_hover: Option<JsonValue>,
    #[serde(rename = "any-pointer", skip_serializing_if = "Option::is_none")]
    pub any_pointer: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<JsonValue>,
    #[serde(rename = "color-gamut", skip_serializing_if = "Option::is_none")]
    pub color_gamut: Option<JsonValue>,
    #[serde(rename = "color-index", skip_serializing_if = "Option::is_none")]
    pub color_index: Option<JsonValue>,
    #[serde(rename = "display-mode", skip_serializing_if = "Option::is_none")]
    pub display_mode: Option<JsonValue>,
    #[serde(rename = "dynamic-range", skip_serializing_if = "Option::is_none")]
    pub dynamic_range: Option<JsonValue>,
    #[serde(rename = "environment-blending", skip_serializing_if = "Option::is_none")]
    pub environment_blending: Option<JsonValue>,
    #[serde(rename = "forced-colors", skip_serializing_if = "Option::is_none")]
    pub forced_colors: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub grid: Option<JsonValue>,
    #[serde(rename = "horizontal-viewport-segments", skip_serializing_if = "Option::is_none")]
    pub horizontal_viewport_segments: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hover: Option<JsonValue>,
    #[serde(rename = "inverted-colors", skip_serializing_if = "Option::is_none")]
    pub inverted_colors: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub monochrome: Option<JsonValue>,
    #[serde(rename = "nav-controls", skip_serializing_if = "Option::is_none")]
    pub nav_controls: Option<JsonValue>,
    #[serde(rename = "overflow-block", skip_serializing_if = "Option::is_none")]
    pub overflow_block: Option<JsonValue>,
    #[serde(rename = "overflow-inline", skip_serializing_if = "Option::is_none")]
    pub overflow_inline: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pointer: Option<JsonValue>,
    #[serde(rename = "prefers-color-scheme", skip_serializing_if = "Option::is_none")]
    pub prefers_color_scheme: Option<JsonValue>,
    #[serde(rename = "prefers-contrast", skip_serializing_if = "Option::is_none")]
    pub prefers_contrast: Option<JsonValue>,
    #[serde(rename = "prefers-reduced-data", skip_serializing_if = "Option::is_none")]
    pub prefers_reduced_data: Option<JsonValue>,
    #[serde(rename = "prefers-reduced-motion", skip_serializing_if = "Option::is_none")]
    pub prefers_reduced_motion: Option<JsonValue>,
    #[serde(rename = "prefers-reduced-transparency", skip_serializing_if = "Option::is_none")]
    pub prefers_reduced_transparency: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scan: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scripting: Option<JsonValue>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub update: Option<JsonValue>,
    #[serde(rename = "vertical-viewport-segments", skip_serializing_if = "Option::is_none")]
    pub vertical_viewport_segments: Option<JsonValue>,
    #[serde(rename = "video-color-gamut", skip_serializing_if = "Option::is_none")]
    pub video_color_gamut: Option<JsonValue>,
    #[serde(rename = "video-dynamic-range", skip_serializing_if = "Option::is_none")]
    pub video_dynamic_range: Option<JsonValue>,
}

/// `emulation.NetworkConditions`
pub type NetworkConditions = crate::emulation::NetworkConditionsOffline;

/// `emulation.NetworkConditionsOffline`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct NetworkConditionsOffline {
    #[serde(rename = "type")]
    pub type_: String,
}

/// `emulation.ScreenArea`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ScreenArea {
    pub width: u64,
    pub height: u64,
}

/// `emulation.ScreenOrientation`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ScreenOrientation {
    pub natural: crate::emulation::ScreenOrientationNatural,
    #[serde(rename = "type")]
    pub type_: crate::emulation::ScreenOrientationType,
}

/// `emulation.ScreenOrientationNatural`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ScreenOrientationNatural {
    #[serde(rename = "portrait")]
    Portrait,
    #[serde(rename = "landscape")]
    Landscape,
}

/// `emulation.ScreenOrientationType`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ScreenOrientationType {
    #[serde(rename = "portrait-primary")]
    PortraitPrimary,
    #[serde(rename = "portrait-secondary")]
    PortraitSecondary,
    #[serde(rename = "landscape-primary")]
    LandscapePrimary,
    #[serde(rename = "landscape-secondary")]
    LandscapeSecondary,
}

/// `emulation.SetForcedColorsModeThemeOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetForcedColorsModeThemeOverrideParameters {
    pub theme: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetForcedColorsModeThemeOverrideResult`
pub type SetForcedColorsModeThemeOverrideResult = crate::EmptyResult;

/// `emulation.SetGeolocationOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetGeolocationOverrideParameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetGeolocationOverrideResult`
pub type SetGeolocationOverrideResult = crate::EmptyResult;

/// `emulation.SetLocaleOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetLocaleOverrideParameters {
    pub locale: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetLocaleOverrideResult`
pub type SetLocaleOverrideResult = crate::EmptyResult;

/// `emulation.SetMediaFeaturesOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetMediaFeaturesOverrideParameters {
    pub features: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetMediaFeaturesOverrideResult`
pub type SetMediaFeaturesOverrideResult = crate::EmptyResult;

/// `emulation.SetNetworkConditionsParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetNetworkConditionsParameters {
    #[serde(rename = "networkConditions")]
    pub network_conditions: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetNetworkConditionsResult`
pub type SetNetworkConditionsResult = crate::EmptyResult;

/// `emulation.SetScreenOrientationOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetScreenOrientationOverrideParameters {
    #[serde(rename = "screenOrientation")]
    pub screen_orientation: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetScreenOrientationOverrideResult`
pub type SetScreenOrientationOverrideResult = crate::EmptyResult;

/// `emulation.SetScreenSettingsOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetScreenSettingsOverrideParameters {
    #[serde(rename = "screenArea")]
    pub screen_area: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetScreenSettingsOverrideResult`
pub type SetScreenSettingsOverrideResult = crate::EmptyResult;

/// `emulation.SetScriptingEnabledParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetScriptingEnabledParameters {
    pub enabled: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetScriptingEnabledResult`
pub type SetScriptingEnabledResult = crate::EmptyResult;

/// `emulation.SetScrollbarTypeOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetScrollbarTypeOverrideParameters {
    #[serde(rename = "scrollbarType")]
    pub scrollbar_type: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetScrollbarTypeOverrideResult`
pub type SetScrollbarTypeOverrideResult = crate::EmptyResult;

/// `emulation.SetTextLayoutModeOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetTextLayoutModeOverrideParameters {
    #[serde(rename = "textLayoutMode")]
    pub text_layout_mode: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetTextLayoutModeOverrideResult`
pub type SetTextLayoutModeOverrideResult = crate::EmptyResult;

/// `emulation.SetTimezoneOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetTimezoneOverrideParameters {
    pub timezone: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetTimezoneOverrideResult`
pub type SetTimezoneOverrideResult = crate::EmptyResult;

/// `emulation.SetTouchOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetTouchOverrideParameters {
    #[serde(rename = "maxTouchPoints")]
    pub max_touch_points: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetTouchOverrideResult`
pub type SetTouchOverrideResult = crate::EmptyResult;

/// `emulation.SetUserAgentOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetUserAgentOverrideParameters {
    #[serde(rename = "userAgent")]
    pub user_agent: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetUserAgentOverrideResult`
pub type SetUserAgentOverrideResult = crate::EmptyResult;

/// `emulation.SetViewportMetaOverrideParameters`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct SetViewportMetaOverrideParameters {
    #[serde(rename = "viewportMeta")]
    pub viewport_meta: JsonValue,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Vec<crate::browsing_context::BrowsingContext>>,
    #[serde(rename = "userContexts", skip_serializing_if = "Option::is_none")]
    pub user_contexts: Option<Vec<crate::browser::UserContext>>,
}

/// `emulation.SetViewportMetaOverrideResult`
pub type SetViewportMetaOverrideResult = crate::EmptyResult;

/// `emulation.TextLayoutMode`
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum TextLayoutMode {
    #[serde(rename = "mobile")]
    Mobile,
}

/// `emulation.setForcedColorsModeThemeOverride`
pub struct SetForcedColorsModeThemeOverride;
impl crate::BidiCommand for SetForcedColorsModeThemeOverride {
    const METHOD: &'static str = "emulation.setForcedColorsModeThemeOverride";
    type Params = crate::emulation::SetForcedColorsModeThemeOverrideParameters;
    type Response = crate::emulation::SetForcedColorsModeThemeOverrideResult;
}

/// `emulation.setGeolocationOverride`
pub struct SetGeolocationOverride;
impl crate::BidiCommand for SetGeolocationOverride {
    const METHOD: &'static str = "emulation.setGeolocationOverride";
    type Params = crate::emulation::SetGeolocationOverrideParameters;
    type Response = crate::emulation::SetGeolocationOverrideResult;
}

/// `emulation.setLocaleOverride`
pub struct SetLocaleOverride;
impl crate::BidiCommand for SetLocaleOverride {
    const METHOD: &'static str = "emulation.setLocaleOverride";
    type Params = crate::emulation::SetLocaleOverrideParameters;
    type Response = crate::emulation::SetLocaleOverrideResult;
}

/// `emulation.setMediaFeaturesOverride`
pub struct SetMediaFeaturesOverride;
impl crate::BidiCommand for SetMediaFeaturesOverride {
    const METHOD: &'static str = "emulation.setMediaFeaturesOverride";
    type Params = crate::emulation::SetMediaFeaturesOverrideParameters;
    type Response = crate::emulation::SetMediaFeaturesOverrideResult;
}

/// `emulation.setNetworkConditions`
pub struct SetNetworkConditions;
impl crate::BidiCommand for SetNetworkConditions {
    const METHOD: &'static str = "emulation.setNetworkConditions";
    type Params = crate::emulation::SetNetworkConditionsParameters;
    type Response = crate::emulation::SetNetworkConditionsResult;
}

/// `emulation.setScreenOrientationOverride`
pub struct SetScreenOrientationOverride;
impl crate::BidiCommand for SetScreenOrientationOverride {
    const METHOD: &'static str = "emulation.setScreenOrientationOverride";
    type Params = crate::emulation::SetScreenOrientationOverrideParameters;
    type Response = crate::emulation::SetScreenOrientationOverrideResult;
}

/// `emulation.setScreenSettingsOverride`
pub struct SetScreenSettingsOverride;
impl crate::BidiCommand for SetScreenSettingsOverride {
    const METHOD: &'static str = "emulation.setScreenSettingsOverride";
    type Params = crate::emulation::SetScreenSettingsOverrideParameters;
    type Response = crate::emulation::SetScreenSettingsOverrideResult;
}

/// `emulation.setScriptingEnabled`
pub struct SetScriptingEnabled;
impl crate::BidiCommand for SetScriptingEnabled {
    const METHOD: &'static str = "emulation.setScriptingEnabled";
    type Params = crate::emulation::SetScriptingEnabledParameters;
    type Response = crate::emulation::SetScriptingEnabledResult;
}

/// `emulation.setScrollbarTypeOverride`
pub struct SetScrollbarTypeOverride;
impl crate::BidiCommand for SetScrollbarTypeOverride {
    const METHOD: &'static str = "emulation.setScrollbarTypeOverride";
    type Params = crate::emulation::SetScrollbarTypeOverrideParameters;
    type Response = crate::emulation::SetScrollbarTypeOverrideResult;
}

/// `emulation.setTextLayoutModeOverride`
pub struct SetTextLayoutModeOverride;
impl crate::BidiCommand for SetTextLayoutModeOverride {
    const METHOD: &'static str = "emulation.setTextLayoutModeOverride";
    type Params = crate::emulation::SetTextLayoutModeOverrideParameters;
    type Response = crate::emulation::SetTextLayoutModeOverrideResult;
}

/// `emulation.setTimezoneOverride`
pub struct SetTimezoneOverride;
impl crate::BidiCommand for SetTimezoneOverride {
    const METHOD: &'static str = "emulation.setTimezoneOverride";
    type Params = crate::emulation::SetTimezoneOverrideParameters;
    type Response = crate::emulation::SetTimezoneOverrideResult;
}

/// `emulation.setTouchOverride`
pub struct SetTouchOverride;
impl crate::BidiCommand for SetTouchOverride {
    const METHOD: &'static str = "emulation.setTouchOverride";
    type Params = crate::emulation::SetTouchOverrideParameters;
    type Response = crate::emulation::SetTouchOverrideResult;
}

/// `emulation.setUserAgentOverride`
pub struct SetUserAgentOverride;
impl crate::BidiCommand for SetUserAgentOverride {
    const METHOD: &'static str = "emulation.setUserAgentOverride";
    type Params = crate::emulation::SetUserAgentOverrideParameters;
    type Response = crate::emulation::SetUserAgentOverrideResult;
}

/// `emulation.setViewportMetaOverride`
pub struct SetViewportMetaOverride;
impl crate::BidiCommand for SetViewportMetaOverride {
    const METHOD: &'static str = "emulation.setViewportMetaOverride";
    type Params = crate::emulation::SetViewportMetaOverrideParameters;
    type Response = crate::emulation::SetViewportMetaOverrideResult;
}

